'use strict';
const fs=require('fs');
const css=fs.readFileSync(__dirname+'/puka.css','utf8');
const art=fs.readFileSync(__dirname+'/puka-v05.css','utf8');
const room=fs.readFileSync(__dirname+'/puka-v05-room.css','utf8');
const motion=fs.readFileSync(__dirname+'/puka-v06.css','utf8');
const cards=fs.readFileSync(__dirname+'/puka-cards-v05.js','utf8');
const character=fs.readFileSync(__dirname+'/puka-character-v06.js','utf8');
const ui=fs.readFileSync(__dirname+'/puka-ui.js','utf8');
const html=fs.readFileSync(__dirname+'/00_OPEN_FIRST.html','utf8');
const sw=fs.readFileSync(__dirname+'/sw.js','utf8');
const fail=m=>{throw new Error(m)};
const has=(body,needle,msg)=>{if(!body.includes(needle))fail(msg)};

has(css,'overflow-x:hidden','viewport overflow guard missing');
has(css,'Phone landscape: true royal composition','phone-landscape royal layout missing');
has(css,'@media(orientation:landscape) and (max-height:650px)','landscape height gate missing');
has(css,'grid-template-columns:150px minmax(0,1fr) 190px','royal mobile three-zone composition missing');
has(css,'.game{min-width:0;order:1}','table-first portrait order missing');
has(ui,"if(isPhone()) return matchMedia('(orientation: portrait)').matches?'portrait':'royal';",'phone orientation must select the presentation route');
has(ui,"$('#identityDetails').open=false",'identity drawer must not block the playfield');
has(ui,'data-quick-suit','ready-table quick suit selector missing');
has(html,'Rotate phone for Royal Table','orientation guidance missing');
has(html,'PUKA v0.6A','v0.6A front-door marker missing');
has(html,'puka-v05.css','v0.5 card body not mounted');
has(html,'puka-v05-room.css','v0.5 environment not mounted');
has(html,'puka-v06.css','v0.6 character styling not mounted');
has(html,'puka-cards-v05.js','v0.5 card organ not mounted');
has(html,'puka-character-v06.js','v0.6 character organ not mounted');
has(sw,"jm-puka-v06a",'service worker cache version not bumped');
has(sw,'puka-v06.css','v0.6 style layer not cached');
has(sw,'puka-character-v06.js','v0.6 character organ not cached');
has(sw,'assets/portrait-academy-backdrop.svg','Portrait Academy asset not cached');
has(sw,'assets/puka-card-back.svg','card-back asset not cached');
has(sw,'assets/royal-felt-medallion.svg','felt asset not cached');
has(art,'Card body: actual card composition','v0.5 card-body art marker missing');
has(art,"html[data-puka-suit='spades']",'suit-responsive art routing missing');
has(art,'@media(max-width:380px)','narrow-phone art guard missing');
has(art,'@media(max-height:560px) and (orientation:landscape)','short-landscape art guard missing');
has(room,'portrait-academy-backdrop.svg','Portrait Academy environment not mounted');
has(cards,"const PIPS",'number-card pip layouts missing');
has(cards,"['J','Q','K']",'court-card route missing');
has(cards,"rank==='A'",'Ace art route missing');
has(cards,'MutationObserver','card art remount observer missing');
has(character,'const seenCards=new Set()','seen-card motion guard missing');
has(character,"return 'joy'",'visible-state joy mood missing');
has(character,"return 'focus'",'visible-state focus mood missing');
has(character,'puka-pot-bump','pot value-change motion hook missing');
has(character,'MutationObserver','character remount observer missing');
has(motion,"html[data-puka-mode='portrait'] .hero-card .card-spirit",'Portrait character layer missing');
has(motion,"html[data-puka-mode='royal'] .card-spirit{display:none!important}",'Royal realism suppression missing');
has(motion,'@media(prefers-reduced-motion:reduce)','reduced-motion guard missing');
has(motion,"data-puka-mood='joy'",'mood expression styling missing');

console.log('PUKA LAYOUT + ART + CHARACTER SOURCE DING PASS');
