'use strict';
const fs=require('fs');
const css=fs.readFileSync(__dirname+'/puka.css','utf8');
const art=fs.readFileSync(__dirname+'/puka-v05.css','utf8');
const room=fs.readFileSync(__dirname+'/puka-v05-room.css','utf8');
const motion=fs.readFileSync(__dirname+'/puka-v06.css','utf8');
const world=fs.readFileSync(__dirname+'/puka-v07.css','utf8');
const material=fs.readFileSync(__dirname+'/puka-v08.css','utf8');
const academy=fs.readFileSync(__dirname+'/puka-v08-academy.css','utf8');
const academyBanner=fs.readFileSync(__dirname+'/assets/puka-academy-banner-v08.svg','utf8');
const cards=fs.readFileSync(__dirname+'/puka-cards-v05.js','utf8');
const character=fs.readFileSync(__dirname+'/puka-character-v06.js','utf8');
const ascent=fs.readFileSync(__dirname+'/puka-world-v07.js','utf8');
const ui=fs.readFileSync(__dirname+'/puka-ui.js','utf8');
const html=fs.readFileSync(__dirname+'/00_OPEN_FIRST.html','utf8');
const sw=fs.readFileSync(__dirname+'/sw.js','utf8');
const fail=m=>{throw new Error(m)};
const has=(body,needle,msg)=>{if(!body.includes(needle))fail(msg)};

has(css,'overflow-x:hidden','viewport overflow guard missing');
has(css,'Phone landscape: true royal composition','phone-landscape royal layout missing');
has(css,'@media(orientation:landscape) and (max-height:650px)','landscape height gate missing');
has(css,'grid-template-columns:150px minmax(0,1fr) 190px','royal mobile three-zone composition missing');
has(css,'.game{min-width:0;order:1}','table-first portrait order missing');
has(ui,"if(isPhone()) return matchMedia('(orientation: portrait)').matches?'portrait':'royal';",'phone orientation must select the presentation route');
has(ui,"$('#identityDetails').open=false",'identity drawer must not block the playfield');
has(ui,'data-quick-suit','ready-table quick suit selector missing');
has(html,'PUKA v0.10A','v0.10A front-door marker missing');
has(html,'puka-v08.css','v0.8 material layer not mounted');
has(html,'puka-v08-academy.css','v0.8 Academy environment not mounted');
has(html,'puka-v07.css','v0.7 world styling not mounted');
has(html,'puka-world-v07.js','v0.7 world organ not mounted');
has(sw,"jm-puka-v10a",'service worker cache version not bumped');
has(sw,'puka-v08.css','v0.8 material style not cached');
has(sw,'puka-v08-academy.css','v0.8 Academy style not cached');
has(sw,'puka-v07.css','v0.7 world style not cached');
has(sw,'puka-world-v07.js','v0.7 world organ not cached');
for(const asset of ['court-lower-v07.svg','court-middle-v07.svg','court-high-v07.svg','court-heir-v07.svg','court-throne-v07.svg','puka-table-inlay-v08.svg','puka-treasury-v08.svg','puka-academy-banner-v08.svg']) has(sw,asset,`${asset} not cached`);
has(art,'Card body: actual card composition','v0.5 card-body art marker missing');
has(room,'portrait-academy-backdrop.svg','Portrait Academy environment not mounted');
has(cards,'const PIPS','number-card pip layouts missing');
has(character,'const seenCards=new Set()','seen-card motion guard missing');
has(motion,"html[data-puka-mode='royal'] .card-spirit{display:none!important}",'Royal realism suppression missing');
has(world,"data-court-tier='throne'",'throne tier styling missing');
has(world,'court-throne-v07.svg','throne room asset routing missing');
has(world,'ascent-plaque','court stage plaque missing');
has(world,'seat-rank-seal','seat rank seal missing');
has(ascent,"'Pauper':{tier:'lower'",'Pauper court mapping missing');
has(ascent,"'Knight':{tier:'high'",'Knight court mapping missing');
has(ascent,"'Heir':{tier:'heir'",'Heir court mapping missing');
has(ascent,"'King':{tier:'throne'",'King throne mapping missing');
has(ascent,"'Queen':{tier:'throne'",'Queen throne mapping missing');
has(ascent,'dataset.courtTier','world state dataset route missing');
has(ascent,'MutationObserver','court ascent remount observer missing');
has(material,'cinematic material pass','v0.8 material source marker missing');
has(material,"puka-table-inlay-v08.svg",'ceremonial table inlay not mounted');
has(material,"puka-treasury-v08.svg",'treasury chip-bank art not mounted');
has(material,"html[data-puka-mode='royal'][data-court-tier='throne'] .table-wrap",'Royal throne material escalation missing');
has(material,"html[data-puka-mode='portrait'] .table-wrap",'Portrait Academy material route missing');
has(material,'@media(max-width:360px)','narrow-phone material guard missing');
has(material,'@media(max-height:560px) and (orientation:landscape)','short-landscape material guard missing');
has(material,'@media(prefers-reduced-motion:reduce)','material reduced-motion guard missing');
has(academy,'Portrait Academy premium environment','Academy source marker missing');
has(academy,'puka-academy-banner-v08.svg','Academy guild banner not mounted');
has(academyBanner,'ACADEMY OF THE FOUR SUITS','Academy banner identity missing');
has(academyBanner,'PUKA Academy guild banner','Academy banner accessibility label missing');
has(academy,'@media(max-width:380px)','Academy narrow-phone guard missing');
has(academy,'@media(prefers-reduced-motion:reduce)','Academy reduced-motion guard missing');

console.log('PUKA INHERITED LAYOUT + ART + CHARACTER + WORLD + MATERIAL + ACADEMY SOURCE DING PASS');
