'use strict';
const fs=require('fs');
const html=fs.readFileSync(__dirname+'/00_OPEN_FIRST.html','utf8');
const css=fs.readFileSync(__dirname+'/puka-v11.css','utf8');
const css12=fs.readFileSync(__dirname+'/puka-v12.css','utf8');
const css13=fs.readFileSync(__dirname+'/puka-v13.css','utf8');
const tableRead=fs.readFileSync(__dirname+'/puka-table-read-v02.css','utf8');
const human=fs.readFileSync(__dirname+'/puka-human-game-v02.js','utf8');
const readLab=fs.readFileSync(__dirname+'/puka-read-lab-v01.js','utf8');
const calibration=fs.readFileSync(__dirname+'/puka-read-calibration-v01.js','utf8');
const pattern=fs.readFileSync(__dirname+'/puka-pattern-window-v01.js','utf8');
const patternCss=fs.readFileSync(__dirname+'/puka-pattern-window-v01.css','utf8');
const deep=fs.readFileSync(__dirname+'/puka-deep-house-v13.js','utf8');
const ui=fs.readFileSync(__dirname+'/puka-ui.js','utf8');
const sw=fs.readFileSync(__dirname+'/sw.js','utf8');
const registry=fs.readFileSync(__dirname+'/registry.json','utf8');
const workflow=fs.readFileSync(__dirname+'/../../.github/workflows/puka-live-proof.yml','utf8');
const browser=fs.readFileSync(__dirname+'/../tests/puka-estate-conformance.spec.mjs','utf8');
const humanBrowser=fs.readFileSync(__dirname+'/../tests/puka-human-game.spec.mjs','utf8');
const patternBrowser=fs.readFileSync(__dirname+'/../tests/puka-pattern-window.spec.mjs','utf8');
const fail=m=>{throw new Error(m)};
const has=(body,needle,msg)=>{if(!body.includes(needle))fail(msg)};

has(html,'PUKA v0.17A','v0.17A front-door marker missing');
has(html,'puka-v11.css','v0.11 conformance layer must remain mounted');
has(html,'puka-v12.css','v0.12 capability layer must remain mounted');
has(html,'puka-v13.css','v0.13 Deep House layer must remain mounted');
has(html,'puka-deep-house-v13.js','v0.13 Deep House organ must remain mounted');
has(html,'puka-table-read-v02.css','v0.14 Human Game presentation layer not mounted');
has(html,'puka-human-game-v02.js','v0.14 Human Game reasoning organ not mounted');
has(html,'puka-read-lab-v01.js','v0.15 Declared Read Lab not mounted');
has(html,'puka-read-calibration-v01.js','v0.16 Counterread calibration not mounted');
has(html,'puka-pattern-window-v01.css','v0.17 Pattern Window presentation not mounted');
has(html,'puka-pattern-window-v01.js','v0.17 Pattern Window reasoning organ not mounted');
has(html,'viewport-fit=cover','safe viewport-fit marker missing');
has(html,'class="skip-link"','skip-link door missing');
has(html,'href="#main"','skip-link must route to main play body');
has(html,'aria-live="polite"','live status announcement missing');
if(/maximum-scale\s*=|user-scalable\s*=\s*no/i.test(html)) fail('zoom restriction is not allowed in the PUKA front door');

has(css,'button,summary{min-height:44px}','44px interaction floor missing');
for(const selector of ['.table-deal,','.deal,','.action,','.suit,','.quick-suit,','.intro summary,','.evidence summary{min-height:44px}']) has(css,selector,`qualified 44px contact guard missing: ${selector}`);
has(css,'.entry-suits button,.quick-suit{min-width:44px}','compact suit target width guard missing');
has(css,'env(safe-area-inset-top)','top safe-area route missing');
has(css,'env(safe-area-inset-bottom)','bottom safe-area route missing');
has(css,'@media(prefers-reduced-motion:reduce)','reduced-motion conformance guard missing');
has(css12,'.raise-size{min-width:44px;min-height:44px}','v0.12 raise contact floor missing');
has(css13,'--puka-d0','Deep House depth role D0 missing');
has(css13,'--puka-d3','Deep House depth role D3 missing');
has(css13,'min-height:max(300px','Deep House protected phone field floor missing');
has(css13,'puka-deep-house-lattice-v13.svg','Deep House field lattice missing');
has(css13,'@media(prefers-reduced-motion:reduce)','Deep House reduced-motion guard missing');
has(tableRead,'.table-read-grid','Human Game table-read composition missing');
has(human,'VISIBLE_ACTION_HISTORY_ONLY','Human Game source membrane marker missing');
has(human,'OBSERVATION != INTERPRETATION != FACT','Human Game founding law missing');
has(readLab,'INTERPRETATION ONLY','Declared Read Lab interpretation boundary missing');
has(calibration,'READ THE TABLE -> READ YOUR READ.','Counterread keeper missing');
has(calibration,'SUPPORTED != PROVED','Counterread support/proof boundary missing');
has(pattern,'A PATTERN MAY EARN ATTENTION. CONTRADICTION KEEPS IT CORRIGIBLE.','Pattern Window keeper missing');
has(pattern,'PATTERN != PROOF','Pattern Window proof boundary missing');
has(pattern,'CONTRADICTION != FAILURE','Pattern Window contradiction boundary missing');
has(patternCss,'min-height:44px','Pattern Window 44px selector contact floor missing');
has(deep,"root.dataset.deepHouse='active'",'Deep House runtime activation marker missing');
has(deep,'root.dataset.contactConsequence','Deep House action consequence marker missing');
has(deep,'root.dataset.fieldContact','Deep House direct field-contact marker missing');

has(ui,"const hideAI=!s.ended||s.endReason==='fold'",'folded hands must not reveal House cards in presentation');
has(ui,'function tableReadInput()','Human Game visible-action packet builder missing');
has(sw,"jm-puka-v17a",'v0.17 service-worker cache marker missing');
for(const marker of ['puka-v11.css','puka-v12.css','puka-v13.css','puka-deep-house-v13.js','puka-table-read-v02.css','puka-human-game-v02.js','puka-read-lab-v01.js','puka-read-calibration-v01.js','puka-pattern-window-v01.js','puka-pattern-window-v01.css']) has(sw,marker,`offline carrier missing: ${marker}`);
has(registry,'JM.PUKA.Room/0.17A','v0.17 registry schema missing');
has(registry,'Pattern != proof of motive','Human Game pattern/motive boundary missing');
has(registry,'Supported != proved','Counterread support/proof law missing');
has(registry,'Pattern != proof','Pattern Window proof law missing');
has(registry,'Contradiction != failure','Pattern Window contradiction law missing');

for(const marker of ['360,height:800','390,height:844','412,height:915','768,height:1024','844,height:390','1366,height:768','1440,height:900','1440,height:1000','scrollWidth','pageerror','console','data-puka-mode','data-next-hand','isMobile:mobile','hasTouch:touch','fullPage:false','protected PUKA table field','page.reload','data-open-raise','data-raise-to','history-row','data-deep-house','data-field-contact','data-contact-consequence']) has(browser,marker,`browser/visual acceptance marker missing: ${marker}`);
for(const marker of ['#tableRead','NO READ EARNED YET','PRESSURE-FORWARD SO FAR','NEXT TEST','houseHole','not.toContain','scrollWidth','pageerror','console','#pukaReadCalibration','HIGH CONFIDENCE IS RUNNING AHEAD','SUPPORTED ≠ PROVED']) has(humanBrowser,marker,`Human Game/Counterread browser acceptance marker missing: ${marker}`);
for(const marker of ['#pukaPatternWindow','CONTRADICTION IS PART OF THE PATTERN','PATTERN ≠ PROOF','data-ppw-size="3"','SECRET_PATTERN_NOTE','A-spades','scrollWidth','pageerror','console']) has(patternBrowser,marker,`Pattern Window browser acceptance marker missing: ${marker}`);
has(workflow,'puka-estate-conformance.spec.mjs','browser acceptance spec not invoked by proof rail');
has(workflow,'puka-human-game.spec.mjs','Human Game browser acceptance spec not invoked by proof rail');
has(workflow,'puka-pattern-window.spec.mjs','Pattern Window browser acceptance spec not invoked by proof rail');
has(workflow,'playwright install --with-deps chromium','Chromium proof environment missing');
has(workflow,'JM.PUKA.ProofReceipt/0.17A','v0.17 proof receipt schema missing from proof rail');

console.log('PUKA v0.17A ESTATE + DEEP HOUSE + HUMAN GAME + DECLARED READ + COUNTERREAD + PATTERN WINDOW CONFORMANCE SOURCE DING PASS');
