#!/usr/bin/env python3
import pathlib, sys
text=pathlib.Path(sys.argv[1]).read_text(errors='replace')
def ordered(items,start=-1):
    pos=start
    for item in items:
        nxt=text.find(item,pos+1)
        if nxt<0: raise SystemExit(f'HOLD: missing or out-of-order trace: {item}')
        pos=nxt
    return pos
base=ordered([
 'JM BOOT IMAGE LOADED','ROUTEOS KERNEL ENTRY','PRIVILEGED EXECUTION ACTIVE',
 'ONEBODY GENERATED ROUTEOS KERNEL LOADED: BLUEPRINT_SHA256','MEMORY INITIALISED: ALLOCATE/RELEASE PASS','INTERRUPT ROUTE ACTIVE',
 'AUTO-GATE / BORING OS: FIRST-CONTACT AUTHORITY + QUARANTINE ACTIVE','ROUTEOS: EXISTING ROUTESCHEDULER + PROOF + RECOVERY ACTIVE','KICPLAY OS: INPUT-TO-ACTION + BODY ACTIVATION ACTIVE','INOUT-16: ORIGIN -> PROCESSING -> EXPRESSION -> RECOVERY ACTIVE','DEVICE INPUT: PS/2 KEYBOARD IRQ1 ACTIVE',
 'BODYREGISTRY: TWO GENERATED USER BODIES REGISTERED','PERMISSIONGATE: INT 0x80 CONTROLLED ENTRY ACTIVE','ROUTESCHEDULER: ENTERING USER BODY 1',
 'GENERATED USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS','GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN',
 'GENERATED USER BODY 2 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS','GENERATED USER BODY 2 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 2 -> KERNEL RETURN',
 'FAULTHOLD: GENERATED USER BODY 2 INVALID OPCODE CAUGHT','RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES'])
contact=ordered([
 'FIRST CONTACT -> AUTO-GATE / BORING OS: SCANCODE 57','INOUT-16 ORIGIN: PHYSICAL KEYBOARD CONTACT','INOUT-16 PROCESSING: AUTO-GATE AUTHORITY CHECK','AUTO-GATE PASS: CONTACT 57 -> AUTHORITY ACCEPTED -> KICPLAY ACTION 1','INOUT-16 EXPRESSION: KICPLAY INPUT BECAME ACTION','KICPLAY OS ACTION 1 -> ROUTEOS STATE 101 -> GENERATED BODY 1 ACTIVATION ROUTE','NO-ERASURE CONTACT LEDGER COUNT 1 SCANCODE 57 ACTION 1 ROUTEOS STATE 101','INOUT-16 RECOVERY: ROUTEOS RETURNS CONTROL TO EXISTING ROUTESCHEDULER',
 'FIRST CONTACT -> AUTO-GATE / BORING OS: SCANCODE 28','INOUT-16 ORIGIN: PHYSICAL KEYBOARD CONTACT','INOUT-16 PROCESSING: AUTO-GATE AUTHORITY CHECK','AUTO-GATE PASS: CONTACT 28 -> AUTHORITY ACCEPTED -> KICPLAY ACTION 2','INOUT-16 EXPRESSION: KICPLAY INPUT BECAME ACTION','KICPLAY OS ACTION 2 -> ROUTEOS STATE 102 -> GENERATED BODY 1 ACTIVATION ROUTE','NO-ERASURE CONTACT LEDGER COUNT 2 SCANCODE 28 ACTION 2 ROUTEOS STATE 102','INOUT-16 RECOVERY: ROUTEOS RETURNS CONTROL TO EXISTING ROUTESCHEDULER'],base)
post=ordered(['GENERATED USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS','GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS'],contact)
if text.find('TIMER TICK ',contact)<0 or text.find('-> ROUTESCHEDULER',contact)<0: raise SystemExit('HOLD: existing RouteScheduler did not continue after contact')
if text.count('ONEBODY GENERATED ROUTEOS KERNEL LOADED: BLUEPRINT_SHA256')!=1: raise SystemExit('HOLD: generated kernel identity count mismatch')
if text.count('FAULTHOLD: GENERATED USER BODY 2 INVALID OPCODE CAUGHT')!=1: raise SystemExit('HOLD: Body 2 fault count mismatch')
if text.count('RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES')!=1: raise SystemExit('HOLD: recovery count mismatch')
if 'FAULTHOLD: GENERATED USER BODY 1' in text: raise SystemExit('HOLD: safe Body 1 faulted')
print('AUTO_GATE_FIRST_CONTACT_TRACE PASS')
print('KICPLAY_INPUT_TO_ACTION_TRACE PASS')
print('INOUT16_CONTACT_ROUTE_TRACE PASS')
print('NO_ERASURE_CONTACT_LEDGER_TRACE PASS')
print('EXISTING_ROUTESCHEDULER_POST_CONTACT PASS')
print('POST_CONTACT_GENERATED_BODY_1_CONTINUATION PASS')
print('ROUTEOS_CONTACT_TO_ACTION_TRACE PASS')
