'use strict';
const PARTS=7, EXPECTED_ROUTES=297, EXPECTED_B64=50428;
let DATA={records:[],districts:[]}, state={view:'home',query:'',filter:'ALL',selected:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function gradeOf(r){if(r.complete||r.grade==='COMPLETE')return 'COMPLETE';const hay=[r.grade,r.subtitle,...(r.tags||[])].join(' ').toUpperCase();for(const g of ['T4','T3','T2','T1'])if(hay.includes(g))return g;return 'ROUTE'}
function gradeClass(g){return g==='COMPLETE'?'complete':g.toLowerCase()}
function b64bytes(s){const clean=s.replace(/\s/g,'');const arr=new Uint8Array(Math.floor(clean.length*3/4));let p=0;for(let i=0;i<clean.length;i+=32768){const bin=atob(clean.slice(i,i+32768));for(let j=0;j<bin.length;j++)arr[p++]=bin.charCodeAt(j)}return arr.slice(0,p)}
async function ungzip(bytes){if(!('DecompressionStream' in window))throw new Error('This browser does not support the built-in gzip reader. Open the dedicated CAUSE MUST PASS body or update Chrome.');const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('gzip'));return new Uint8Array(await new Response(stream).arrayBuffer())}
async function load(){try{const status=$('#loadStatus');const texts=[];for(let i=1;i<=PARTS;i++){status.textContent=`Fetching payload section ${i} of ${PARTS}…`;const path=`./data/v0_4/part-${String(i).padStart(2,'0')}.txt?v=0401`;const res=await fetch(path,{cache:'no-store'});if(!res.ok)throw new Error(`Payload section ${i} returned ${res.status}.`);texts.push((await res.text()).trim())}const joined=texts.join('');if(joined.length!==EXPECTED_B64)throw new Error(`Payload length mismatch: ${joined.length} instead of ${EXPECTED_B64}.`);status.textContent='Opening 297 routes…';const raw=await ungzip(b64bytes(joined));DATA=JSON.parse(new TextDecoder().decode(raw));if(!Array.isArray(DATA.records)||DATA.records.length!==EXPECTED_ROUTES)throw new Error(`Route count mismatch: ${DATA.records?.length||0} instead of ${EXPECTED_ROUTES}.`);boot();$('#loading').hidden=true}catch(err){console.error(err);$('#loadStatus').textContent='The Theory Wing payload did not open.';$('#loadError').innerHTML=`${esc(err.message)}<br><br><a class="btn" href="./cause-must-pass/00_OPEN_FIRST.html">Open CAUSE MUST PASS</a>`}}
function boot(){renderFilters();renderList();renderFeatures();renderProjects();renderDistricts();bind();const params=new URLSearchParams(location.hash.replace(/^#/,''));const id=params.get('body');if(id)openRecord(id);}
function bind(){$$('[data-view]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));$$('[data-open]').forEach(b=>b.addEventListener('click',()=>openRecord(b.dataset.open)));$('#search').addEventListener('input',e=>{state.query=e.target.value;renderList()});window.addEventListener('hashchange',()=>{const id=new URLSearchParams(location.hash.replace(/^#/,'')).get('body');if(id&&id!==state.selected)openRecord(id,true)})}
function go(view){state.view=view;$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.viewPanel===view));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view!=='library')$('#reader').classList.remove('open')}
function renderFilters(){const grades=['ALL','COMPLETE','T4','T3','T2','T1'];$('#filters').innerHTML=grades.map(g=>`<button class="filter ${g==='ALL'?'active':''}" data-filter="${g}">${g}</button>`).join('');$$('[data-filter]').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderList()})}
function filtered(){const q=state.query.trim().toLowerCase();return DATA.records.filter(r=>(state.filter==='ALL'||gradeOf(r)===state.filter)&&(!q||[r.title,r.subtitle,r.shelf,r.lane,r.identity,r.claim,r.source,(r.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)))}
function renderList(){if(!DATA.records.length)return;const rows=filtered();$('#resultCount').textContent=`${rows.length} of ${DATA.records.length} routes`;$('#results').innerHTML=rows.map(r=>`<button class="row ${state.selected===r.id?'active':''}" data-id="${esc(r.id)}"><b>${esc(r.n)} · ${esc(r.title)}</b><small>${esc(gradeOf(r))} · ${esc(r.shelf)}</small></button>`).join('')||'<div class="source-note">No routes match this search.</div>';$$('.row[data-id]').forEach(b=>b.onclick=()=>openRecord(b.dataset.id))}
function openRecord(id,fromHash=false){const r=DATA.records.find(x=>x.id===id);if(!r)return;state.selected=id;go('library');renderList();const g=gradeOf(r);const route=r.route?(r.route.startsWith('theory/')?'../'+r.route:r.route):'';$('#reader').className='card reader open';$('#reader').innerHTML=`<button class="btn reader-close" style="display:none" id="readerClose">← Back to list</button><div class="meta"><span class="tag ${gradeClass(g)}">${esc(g)}</span><span class="tag">${esc(r.shelf)}</span><span class="tag">${esc(r.n)}</span></div><h2>${esc(r.title)}</h2><div class="subtitle">${esc(r.subtitle||r.identity)}</div><div class="claim"><b>Core route</b><br>${esc(r.claim||r.identity)}</div>${r.keepers?.length?`<h3>Keeper lines</h3><ul class="keeper-list">${r.keepers.map(k=>`<li>${esc(k)}</li>`).join('')}</ul>`:''}<div class="body-copy">${esc(r.body||r.identity)}</div><div class="reader-footer"><b>Source state:</b> ${esc(r.source||'Project-source census')}<br><b>Boundary:</b> ${r.complete?'Complete within its declared scope; universal empirical validity is not silently claimed.':'Recovered route; current grade does not silently crown completion.'}${route?`<div class="actions"><a class="btn primary" href="${esc(route)}">Open dedicated full public body ↗</a></div>`:''}</div>`;$('#readerClose')?.addEventListener('click',()=>$('#reader').classList.remove('open'));if(!fromHash)history.replaceState(null,'',`#body=${encodeURIComponent(id)}`);$('#reader').scrollTop=0}
function renderFeatures(){const ids=['cause-must-pass','medium-dependency-law','contact-causation-authority','actual-mental-health','project-contact-field-theory','project-spalktalk','project-benefitmerge-theory','project-first-house-palace-place-to-lace-v0-1'];const rs=ids.map(id=>DATA.records.find(r=>r.id===id)).filter(Boolean);$('#features').innerHTML=rs.map(r=>featureHTML(r)).join('');$$('#features [data-id]').forEach(x=>x.onclick=()=>openRecord(x.dataset.id))}
function featureHTML(r){const g=gradeOf(r);return `<article class="card feature" tabindex="0" role="button" data-id="${esc(r.id)}"><div class="meta"><span class="tag ${gradeClass(g)}">${esc(g)}</span><span class="tag">${esc(r.shelf)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.identity||r.claim)}</p><div class="source-note">${esc(r.source)}</div></article>`}
function projectChildren(tag){return DATA.records.filter(r=>(r.tags||[]).includes(tag))}
function renderProjects(){const defs=[{id:'bringing-it-all-together',tag:'bringing-it-all-together',label:'Bringing It All Together',count:76},{id:'first-stage-jungle',tag:'first-stage-jungle',label:'First Stage / Step Into / Out of the Jungle',count:187}];$('#projectGrid').innerHTML=defs.map(d=>{const kids=projectChildren(d.tag).filter(r=>r.id!==d.id);return `<article class="card project"><div class="eyebrow">Project trunk</div><div class="count">${d.count}</div><h2>${esc(d.label)}</h2><p class="lead" style="font-size:15px">${esc(DATA.records.find(r=>r.id===d.id)?.identity||'Mounted project-source children')}</p><div class="actions"><button class="btn primary" data-id="${d.id}">Open trunk</button><button class="btn" data-project="${d.tag}">Filter its children</button></div><div class="child-list">${kids.slice(0,18).map(r=>`<button class="child" data-id="${r.id}">${esc(r.title)}</button>`).join('')}</div></article>`}).join('');$$('#projectGrid [data-id]').forEach(b=>b.onclick=()=>openRecord(b.dataset.id));$$('[data-project]').forEach(b=>b.onclick=()=>{go('library');state.query=b.dataset.project;$('#search').value=state.query;renderList()})}
function renderDistricts(){$('#districtGrid').innerHTML=DATA.districts.map(d=>`<article class="card district"><div class="eyebrow">District</div><h3>${esc(d.name)}</h3>${d.bodies.map(n=>`<button data-term="${esc(n)}">${esc(n)} →</button>`).join('')}</article>`).join('');$$('[data-term]').forEach(b=>b.onclick=()=>{go('library');state.query=b.dataset.term;$('#search').value=state.query;renderList()})}
load();
