#!/usr/bin/env python3
import pathlib, sys
text = pathlib.Path(sys.argv[1]).read_text(errors='replace')
ordered = [
    'JM BOOT IMAGE LOADED','ROUTEOS KERNEL ENTRY','PRIVILEGED EXECUTION ACTIVE',
    'MEMORY INITIALISED: ALLOCATE/RELEASE PASS','INTERRUPT ROUTE ACTIVE',
    'BODYREGISTRY: TWO GENERATED USER BODIES REGISTERED',
    'ONEBODY GENERATED USER BODY 1 LOADED: SOURCE_SHA256',
    'ONEBODY GENERATED USER BODY 2 LOADED: SOURCE_SHA256',
    'PERMISSIONGATE: INT 0x80 CONTROLLED ENTRY ACTIVE','DEVICE OUTPUT: JM-CONTROLLED SERIAL ACTIVE',
    'ROUTESCHEDULER: ENTERING USER BODY 1',
    'GENERATED USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
    'GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN',
    'GENERATED USER BODY 2 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
    'GENERATED USER BODY 2 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 2 -> KERNEL RETURN',
    'FAULTHOLD: GENERATED USER BODY 2 INVALID OPCODE CAUGHT',
    'RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES',
    'GENERATED USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
    'GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN',
]
pos = -1
for item in ordered:
    new = text.find(item, pos + 1)
    if new < 0: raise SystemExit(f'HOLD: missing or out-of-order trace: {item}')
    pos = new
if 'TIMER TICK ' not in text or '-> ROUTESCHEDULER' not in text: raise SystemExit('HOLD: no dynamic PIT timer -> RouteScheduler receipt')
fault = text.count('FAULTHOLD: GENERATED USER BODY 2 INVALID OPCODE CAUGHT')
recovery = text.count('RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES')
if fault != 1 or recovery != 1: raise SystemExit(f'HOLD: fault/recovery count mismatch: fault={fault} recovery={recovery}')
if 'FAULTHOLD: GENERATED USER BODY 1' in text: raise SystemExit('HOLD: safe generated Body 1 faulted')
print('TWO_GENERATED_BODIES_TRACE PASS')
print('DISTINCT_ROUTE_STATE_1_AND_2 PASS')
print('GENERATED_BODY_2_FAULT_OWNERSHIP PASS')
print('POST_FAULT_GENERATED_BODY_1_CONTINUATION PASS')
print('TIMER_DRIVEN_TWO_BODY_SCHEDULER_TRACE PASS')
