(()=>{'use strict';
const $=id=>document.getElementById(id), $$=q=>[...document.querySelectorAll(q)], NOW=()=>new Date().toISOString(), RELEASE='0.5.0';
let db,manifest,pack,selected=null,filter='all',protectedBodies=new Map(),recent=JSON.parse(localStorage.getItem('jm-gb-recent-v05')||'[]'),lastFocus=null,lastAudit=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const bytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const req=r=>new Promise((ok,no)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});
const os=(name,mode='readonly')=>db.transaction(name,mode).objectStore(name);
const all=name=>req(os(name).getAll()), put=(name,value)=>req(os(name,'readwrite').put(value)), remove=(name,key)=>req(os(name,'readwrite').delete(key));
const hash=async data=>[...new Uint8Array(await crypto.subtle.digest('SHA-256',typeof data==='string'?new TextEncoder().encode(data):data))].map(x=>x.toString(16).padStart(2,'0')).join('');
function toast(text,bad=false){const n=$('toast');n.textContent=text;n.className='toast show'+(bad?' bad':'');clearTimeout(toast.t);toast.t=setTimeout(()=>n.className='toast',2600)}
function progress(value,text){value=Math.max(0,Math.min(100,Math.round(value)));$('loadPct').textContent=value+'%';$('loadBar').style.width=value+'%';$('loadText').textContent=text;$('loadProgress').setAttribute('aria-valuenow',value)}
async function receipt(type,body='Games&Beyond',extra={}){if(!db)return;await put('receipts',{key:Date.now()+Math.random(),time:NOW(),type,body,extra});stats();renderReceipts()}
function findBody(id){return pack?.bodies.find(x=>x.id===id)}
function download(name,data,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function openDB(){return new Promise((ok,no)=>{const r=indexedDB.open('jm-games-beyond-public-v05',1);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('edits'))d.createObjectStore('edits',{keyPath:'id'});if(!d.objectStoreNames.contains('revisions'))d.createObjectStore('revisions',{keyPath:'key'}).createIndex('bodyId','bodyId');if(!d.objectStoreNames.contains('receipts'))d.createObjectStore('receipts',{keyPath:'key'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
async function decodePayload(){
 progress(2,'Opening payload manifest…');manifest=await fetch(`payload-manifest.json?release=${RELEASE}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`Manifest HTTP ${r.status}`);return r.json()});$('expectedStat').textContent=manifest.fullTargetCount||manifest.bodyCount;
 let b64='';for(let i=0;i<manifest.parts;i++){const p=manifest.partPattern.includes('{index:03d}')?manifest.partPattern.replace('{index:03d}',String(i).padStart(3,'0')):manifest.partPattern;b64+=(await fetch(`${p}?release=${RELEASE}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`${p} HTTP ${r.status}`);return r.text()})).trim();progress(5+(i+1)/manifest.parts*45,`Receiving protected payload ${i+1}/${manifest.parts}`)}
 if(b64.length!==manifest.base64Chars)throw Error(`Payload length ${b64.length}/${manifest.base64Chars}`);const raw=atob(b64),compressed=Uint8Array.from(raw,c=>c.charCodeAt(0));if(await hash(compressed)!==manifest.compressedSha256)throw Error('Compressed payload digest mismatch');progress(55,'Decompressing exact Eco/Estate bodies…');
 let text=await new Promise((ok,no)=>LZMA.decompress([...compressed],(value,error)=>error?no(error):ok(value),p=>progress(55+25*p,'Decompressing exact bodies…')));if(typeof text!=='string')text=new TextDecoder().decode(Uint8Array.from(text));if(await hash(text)!==manifest.rawSha256)throw Error('Full payload digest mismatch');const result=JSON.parse(text);if(!Array.isArray(result.bodies)||result.bodies.length!==manifest.payloadBodyCount)throw Error('Payload body count mismatch');
 progress(82,'Mounting committed House bodies…');for(let i=0;i<(manifest.extraBodies||[]).length;i++){const meta=manifest.extraBodies[i],html=await fetch(`${meta.path}?release=${RELEASE}`,{cache:'no-store'}).then(r=>{if(!r.ok)throw Error(`${meta.path} HTTP ${r.status}`);return r.text()});if(!/<html|<!doctype/i.test(html))throw Error(`${meta.id} is not HTML`);result.bodies.push({...meta,html,hash:await hash(html),size:new Blob([html]).size,mounted:true,status:'MOUNTED',sourceName:meta.path,bundled:true,updatedAt:NOW()});progress(82+(i+1)/(manifest.extraBodies.length||1)*12,`Mounting committed body ${i+1}/${manifest.extraBodies.length}`)}
 const edits=await all('edits');for(const edit of edits){const at=result.bodies.findIndex(x=>x.id===edit.id);at>=0?result.bodies[at]={...result.bodies[at],...edit,edited:true}:result.bodies.push({...edit,mounted:true,status:'MOUNTED',edited:true})}
 if(result.bodies.length<(manifest.builtInBodyCount||manifest.bodyCount))throw Error('Built-in body count short');pack=result;protectedBodies=new Map(result.bodies.map(x=>[x.id,structuredClone(x)]));progress(100,`${result.bodies.length} bodies mounted. Full target: ${manifest.fullTargetCount||result.bodies.length}.`);$('status').textContent=`${result.bodies.length} MOUNTED · ${manifest.fullTargetCount||result.bodies.length} FULL`;$('status').className='status ok';$('enterBtn').disabled=false;await receipt('ACCESSIBLE_PUBLIC_HOUSE_BOOT','Games&Beyond',{bodies:result.bodies.length,fullTarget:manifest.fullTargetCount,accessibilityVersion:'0.5'});renderAll();setTimeout(()=>runAudit(false),30)
}
function card(b){const a=b.accessibilityAudit;return `<article class="room ${b.id===selected?'selected':''}" aria-labelledby="room-${esc(b.id)}"><h3 id="room-${esc(b.id)}">${esc(b.name)} <span>${esc(b.version||'')}</span></h3><p>${esc(b.role||'Sovereign mounted body')}</p><div class="tags"><span class="tag">${esc(b.category||'Room')}</span><span class="tag live">MOUNTED</span><span class="tag">${bytes(new Blob([b.html]).size)}</span>${b.edited?'<span class="tag live">CREATOR REVISION</span>':''}${a?`<span class="tag ${a.grade==='A'?'live':''}">ACCESS ${a.grade}</span>`:''}</div><div class="roomActions"><button data-play="${esc(b.id)}" aria-label="Open ${esc(b.name)}">OPEN BODY</button><button data-edit="${esc(b.id)}">EDIT</button><button data-export="${esc(b.id)}">EXPORT</button></div></article>`}
function shown(){const q=($('search')?.value||'').toLowerCase();return (pack?.bodies||[]).filter(b=>(filter==='all'||b.category===filter)&&(!q||[b.id,b.name,b.version,b.role,b.category,b.stage].join(' ').toLowerCase().includes(q)))}
function bindCards(){$$('[data-play]').forEach(x=>x.onclick=()=>openBody(x.dataset.play));$$('[data-edit]').forEach(x=>x.onclick=()=>editBody(x.dataset.edit));$$('[data-export]').forEach(x=>x.onclick=()=>exportBody(x.dataset.export))}
function renderRooms(){const bodies=shown();$('roomRail').innerHTML=bodies.length?bodies.map(card).join(''):'<div class="empty">No rooms match that route.</div>';$('searchSummary').textContent=`${bodies.length} rooms shown`;bindCards()}
function renderFilters(){const cats=['all',...new Set((pack?.bodies||[]).map(x=>x.category))];$('filters').innerHTML=cats.map(x=>`<button class="filter ${x===filter?'active':''}" data-cat="${esc(x)}" aria-pressed="${x===filter}">${x==='all'?'ALL ROOMS':esc(x)}</button>`).join('');$$('[data-cat]').forEach(x=>x.onclick=()=>{filter=x.dataset.cat;renderFilters();renderRooms()})}
function renderRecent(){const bodies=recent.map(findBody).filter(Boolean).slice(0,5);$('recentRooms').innerHTML=bodies.length?bodies.map(card).join(''):'<div class="empty">Open a room and the House will remember the route.</div>';bindCards()}
async function stats(){$('mountedStat').textContent=pack?.bodies.length||0;$('editedStat').textContent=(await all('edits')).length;$('receiptStat').textContent=(await all('receipts')).length}
function renderAll(){renderFilters();renderRooms();renderRecent();stats();if(selected&&findBody(selected))editBody(selected)}
function view(name,focus=true){$$('.view').forEach(x=>x.hidden=x.dataset.view!==name);$$('.nav button').forEach(x=>{const on=x.dataset.view===name;x.classList.toggle('active',on);x.setAttribute('aria-selected',on);x.tabIndex=on?0:-1});if(focus){const h=document.querySelector(`.view[data-view="${name}"] h1,.view[data-view="${name}"] h2`);if(h){h.tabIndex=-1;h.focus({preventScroll:true})}}scrollTo({top:0,behavior:document.documentElement.classList.contains('reduced-motion')?'auto':'smooth'})}
function runtimeLayer(doc,b){const notes=[];if(!doc.documentElement.lang){doc.documentElement.lang='en';notes.push('language declared')}if(!doc.title.trim()){doc.title=`${b.name} ${b.version||''}`;notes.push('title supplied')}const style=doc.createElement('style');style.dataset.jmAccessibility='runtime';style.textContent='*:focus-visible{outline:3px solid #fff36b!important;outline-offset:3px!important}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}}button,input,select,textarea,a,[role=button]{min-height:44px}';doc.head?.append(style);let unnamed=0;doc.querySelectorAll('button,[role=button],a').forEach((x,i)=>{if(!(x.getAttribute('aria-label')||x.getAttribute('aria-labelledby')||x.textContent||x.title||'').trim()){x.setAttribute('aria-label',`Control ${i+1} in ${b.name}`);unnamed++}});if(unnamed)notes.push(`${unnamed} controls named`);let canvases=0;doc.querySelectorAll('canvas').forEach((x,i)=>{if(!x.getAttribute('aria-label')&&!x.getAttribute('aria-labelledby')){x.setAttribute('role','img');x.setAttribute('aria-label',`${b.name} interactive canvas ${i+1}`);canvases++}});if(canvases)notes.push(`${canvases} canvases named`);doc.querySelectorAll('iframe').forEach((x,i)=>{if(!x.title)x.title=`Embedded content ${i+1} in ${b.name}`});return notes}
async function openBody(id,override=null){const b=findBody(id);if(!b)return toast('Room unavailable',true);recent=[id,...recent.filter(x=>x!==id)].slice(0,8);localStorage.setItem('jm-gb-recent-v05',JSON.stringify(recent));renderRecent();selected=id;lastFocus=document.activeElement;$('dialogTitle').textContent=`${b.name} ${b.version||''}`;$('dialogMeta').textContent=`${b.category||'Room'} · ${b.stage||'MOUNTED'} · exact source in wrapper`;$('bodySummary').textContent='Runtime assistance is applied only in this opening. Stored source remains unchanged.';$('bodyFrame').title=`${b.name} ${b.version||''} mounted body`;$('bodyFrame').srcdoc=override??b.html;$('bodyDialog').showModal();$('bodyFrame').onload=()=>{try{const notes=runtimeLayer($('bodyFrame').contentDocument,b);$('bodySummary').textContent=notes.length?`Runtime assistance: ${notes.join('; ')}. Stored source remains unchanged.`:'No runtime repair was required by this limited host scanner.'}catch{}};await receipt('BODY_OPENED_ACCESSIBLE_WRAPPER',b.name,{id,edited:!!b.edited})}
function closeBody(){$('bodyDialog').close();$('bodyFrame').srcdoc='';lastFocus?.focus?.()}
function separateBody(){const b=findBody(selected);if(!b)return;const url=URL.createObjectURL(new Blob([$('bodyFrame').srcdoc||b.html],{type:'text/html'})),a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.click();setTimeout(()=>URL.revokeObjectURL(url),120000);receipt('BODY_OPENED_SEPARATE',b.name,{id:b.id})}
function editBody(id){const b=findBody(id);if(!b)return;selected=id;$('editEmpty').hidden=true;$('workspace').hidden=false;$('bodyName').value=b.name||'';$('bodyVersion').value=b.version||'';$('bodyRole').value=b.role||'';$('bodyCategory').value=b.category||'';$('bodyStage').value=b.stage||'';$('source').value=b.html||'';$('bodyState').textContent=`${b.edited?'Creator revision':'Protected delivery body'} · ${b.hash||'hash pending'}`;view('edit',false);renderRooms()}
async function saveEdit(sourceOnly=false){const b=findBody(selected);if(!b)return;await put('revisions',{key:Date.now()+Math.random(),bodyId:b.id,time:NOW(),body:structuredClone(b)});if(!sourceOnly)Object.assign(b,{name:$('bodyName').value.trim()||b.name,version:$('bodyVersion').value.trim(),role:$('bodyRole').value.trim(),category:$('bodyCategory').value.trim(),stage:$('bodyStage').value.trim()});b.html=$('source').value;b.hash=await hash(b.html);b.edited=true;b.updatedAt=NOW();await put('edits',structuredClone(b));await receipt('CREATOR_REVISION_SAVED',b.name,{id:b.id,hash:b.hash});renderAll();toast('Creator revision saved')}
async function undo(){const b=findBody(selected);if(!b)return;const revs=(await all('revisions')).filter(x=>x.bodyId===b.id).sort((a,b)=>b.key-a.key);if(!revs.length)return toast('No revision to undo',true);Object.assign(b,revs[0].body,{edited:true});await put('edits',structuredClone(b));await remove('revisions',revs[0].key);await receipt('SOURCE_UNDO',b.name,{from:revs[0].time});renderAll();editBody(b.id);toast('Previous revision restored')}
async function restore(){const base=protectedBodies.get(selected),at=pack.bodies.findIndex(x=>x.id===selected);if(!base||at<0)return;pack.bodies[at]=structuredClone(base);await remove('edits',selected);await receipt('PROTECTED_SOURCE_RESTORED',base.name,{id:selected});renderAll();editBody(selected);toast('Protected source restored')}
async function exportBody(id){const b=findBody(id);if(!b)return;download((b.sourceName||`${b.id}.html`).split('/').pop(),b.html,'text/html');await receipt('BODY_EXPORTED',b.name,{id,hash:b.hash,bytes:new Blob([b.html]).size})}
function audit(b){const html=b.html||'',issues=[],add=(code,severity,message,count=1)=>issues.push({code,severity,message,count});if(!/<html\b[^>]*\blang\s*=/i.test(html))add('HTML_LANG','moderate','Language not declared');if(!/<title\b[^>]*>\s*[^<]+/i.test(html))add('DOCUMENT_TITLE','serious','Title missing');if(!/<main\b|role\s*=\s*["']main["']/i.test(html))add('MAIN_LANDMARK','moderate','Main landmark not detected');if(!/<h1\b/i.test(html))add('H1','moderate','H1 not detected');const alt=(html.match(/<img\b[^>]*>/gi)||[]).filter(x=>! /\balt\s*=/i.test(x)).length;if(alt)add('IMAGE_ALT','serious','Images missing alt',alt);const frames=(html.match(/<iframe\b[^>]*>/gi)||[]).filter(x=>! /\btitle\s*=/i.test(x)).length;if(frames)add('IFRAME_TITLE','serious','Frames missing titles',frames);const canvas=(html.match(/<canvas\b[^>]*>/gi)||[]).filter(x=>! /(aria-label|aria-labelledby|role)\s*=/i.test(x)).length;if(canvas)add('CANVAS_NAME','serious','Canvases missing names',canvas);if(/@keyframes|animation\s*:|transition\s*:/i.test(html)&&! /prefers-reduced-motion/i.test(html))add('REDUCED_MOTION','moderate','Motion without reduced-motion rule');if(/user-scalable\s*=\s*no|maximum-scale\s*=\s*1/i.test(html))add('ZOOM_RESTRICTION','serious','Viewport restricts zoom');const serious=issues.filter(x=>x.severity==='serious').reduce((n,x)=>n+x.count,0),moderate=issues.filter(x=>x.severity==='moderate').reduce((n,x)=>n+x.count,0);return{id:b.id,name:b.name,version:b.version,grade:serious===0&&moderate<=1?'A':serious<=2&&moderate<=4?'B':'C',issueCount:issues.reduce((n,x)=>n+x.count,0),issues,bytes:new Blob([html]).size}}
async function runAudit(open=true){if(!pack)return;const results=pack.bodies.map(b=>{const a=audit(b);b.accessibilityAudit=a;return a});lastAudit={schema:'JM.AccessibilitySweep/0.5-runtime',checkedAt:NOW(),bodyCount:results.length,claimBoundary:'Automated static preflight and runtime assistance; not a WCAG certification.',results};await receipt('ACCESSIBILITY_SWEEP','Games&Beyond',{bodyCount:results.length,grades:results.reduce((n,x)=>(n[x.grade]=(n[x.grade]||0)+1,n),{})});renderAudit();renderRooms();if(open)view('access');toast(`${results.length}-body accessibility sweep complete`)}
function renderAudit(){if(!lastAudit)return;const grades=lastAudit.results.reduce((n,x)=>(n[x.grade]=(n[x.grade]||0)+1,n),{});$('a11ySummary').textContent=`Static preflight: A ${grades.A||0} · B ${grades.B||0} · C ${grades.C||0}. Runtime help remains separate from stored source.`;$('a11yList').innerHTML=lastAudit.results.map(a=>`<article class="auditCard"><div style="display:flex;align-items:center;gap:9px"><span class="grade ${a.grade}">${a.grade}</span><div><b>${esc(a.name)} · ${esc(a.version||'')}</b><span>${a.issueCount} detected items · ${bytes(a.bytes)}</span></div></div>${a.issues.length?`<details><summary>Review items</summary><ul>${a.issues.map(x=>`<li><strong>${esc(x.severity.toUpperCase())}</strong> · ${esc(x.message)}${x.count>1?' × '+x.count:''}</li>`).join('')}</ul></details>`:'<p>No issue in this limited rule set.</p>'}</article>`).join('')}
async function proof(){const results=[];for(const b of pack.bodies)results.push({id:b.id,name:b.name,html:/<html|<!doctype/i.test(b.html),bytes:new Blob([b.html]).size,digest:await hash(b.html),edited:!!b.edited});const built=manifest.builtInBodyCount||manifest.bodyCount,full=manifest.fullTargetCount||built,pass=results.length>=built&&results.every(x=>x.html),fullMount=results.length===full,report={schema:'JM.GamesBeyond.PublicProof/0.5',checkedAt:NOW(),pass,fullMount,bodyCount:results.length,builtInExpected:built,fullTarget:full,accessibilityAudit:!!lastAudit,results};$('proofBox').textContent=JSON.stringify(report,null,2);await receipt(fullMount?'FULL_23_BODY_HOUSE_PROOF':'BUILT_IN_HOUSE_PROOF',pass?'DING':'BUGG',{pass,fullMount,bodyCount:results.length,fullTarget:full});view('proof');toast(pass?(fullMount?'23-body full House proof DING':`${results.length}-body built-in proof DING`):'Proof found a gap',!pass)}
async function exportHouse(){download('GAMES_BEYOND_FULL_HOUSE_v0_5_LOCAL_EXPORT.json',JSON.stringify({...pack,schema:'JM.GamesBeyondHouse/0.5-public-export',exportedAt:NOW(),localReceipts:await all('receipts'),accessibility:lastAudit},null,2),'application/json');await receipt('FULL_HOUSE_EXPORTED','Games&Beyond',{bodies:pack.bodies.length})}
async function importHouse(file){try{const incoming=JSON.parse(await file.text());if(!Array.isArray(incoming.bodies))throw Error('No bodies array');let added=0,updated=0;for(const item of incoming.bodies){if(!item?.id||!item.html||!/<html|<!doctype/i.test(item.html))continue;const at=pack.bodies.findIndex(x=>x.id===item.id);if(at>=0){pack.bodies[at]={...pack.bodies[at],...item,mounted:true,status:'MOUNTED',edited:true};updated++}else{pack.bodies.push({...item,mounted:true,status:'MOUNTED',edited:true});protectedBodies.set(item.id,structuredClone(item));added++}await put('edits',structuredClone(findBody(item.id)))}const full=manifest.fullTargetCount||23,done=pack.bodies.length>=full;$('status').textContent=done?`${full}/${full} FULL HOUSE`:`${pack.bodies.length} MOUNTED · ${full} FULL`;$('status').className='status '+(done?'ok':'');await receipt(done?'ECO_ESTATE_FULL_HOUSE_IMPORTED':'HOUSE_BACKUP_IMPORTED','Games&Beyond',{incoming:incoming.bodies.length,added,updated,mounted:pack.bodies.length,fullTarget:full});renderAll();await runAudit(false);toast(done?`${full}-body full House mounted`:`Import added ${added} bodies`)}catch(err){toast('Import failed: '+err.message,true)}}
async function clearEdits(){if(!confirm('Clear all local edits and imported bodies?'))return;for(const x of await all('edits'))await remove('edits',x.id);location.reload()}
async function renderReceipts(){if(!db)return;const rows=(await all('receipts')).sort((a,b)=>b.key-a.key).slice(0,100);$('receipts').innerHTML=rows.map(x=>`<div class="receipt"><b>${esc(x.type)} · ${esc(x.body)}</b><span>${esc(x.time)}\n${esc(JSON.stringify(x.extra||{}))}</span></div>`).join('')||'<div class="empty">No receipts yet.</div>'}
function toggle(cls,id){const on=!document.documentElement.classList.contains(cls);document.documentElement.classList.toggle(cls,on);localStorage.setItem('jm-gb-'+cls,on);$(id).setAttribute('aria-pressed',on);if(cls==='large-text')document.documentElement.style.setProperty('--scale',on?'1.18':'1')}
function bind(){const nav=$$('.nav button');nav.forEach((b,i)=>{b.onclick=()=>view(b.dataset.view);b.onkeydown=e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key))return;e.preventDefault();const j=e.key==='Home'?0:e.key==='End'?nav.length-1:(i+(e.key==='ArrowRight'?1:-1)+nav.length)%nav.length;nav[j].focus();view(nav[j].dataset.view)}});$('enterBtn').onclick=()=>view('rooms');$('reloadBtn').onclick=()=>location.reload();$('search').oninput=renderRooms;$('proofQuick').onclick=$('runProof').onclick=proof;$('savePassport').onclick=()=>saveEdit(false);$('saveSource').onclick=()=>saveEdit(true);$('undoSource').onclick=undo;$('restoreBody').onclick=restore;$('exportBody').onclick=()=>exportBody(selected);$('testSource').onclick=()=>openBody(selected,$('source').value);$('exportHouse').onclick=exportHouse;$('importHouse').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{if(e.target.files[0])importHouse(e.target.files[0]);e.target.value=''};$('clearEdits').onclick=clearEdits;$('closeDialog').onclick=closeBody;$('openExternal').onclick=separateBody;$('bodyDialog').addEventListener('cancel',e=>{e.preventDefault();closeBody()});$('runA11y').onclick=()=>runAudit(true);$('exportA11y').onclick=()=>lastAudit?download('GAMES_BEYOND_ACCESSIBILITY_REPORT_v0_5.json',JSON.stringify(lastAudit,null,2),'application/json'):toast('Run the audit first',true);$('contrastBtn').onclick=()=>toggle('high-contrast','contrastBtn');$('textBtn').onclick=()=>toggle('large-text','textBtn');$('motionBtn').onclick=()=>toggle('reduced-motion','motionBtn');for(const [cls,id] of [['high-contrast','contrastBtn'],['large-text','textBtn'],['reduced-motion','motionBtn']]){const on=localStorage.getItem('jm-gb-'+cls)==='true';document.documentElement.classList.toggle(cls,on);$(id).setAttribute('aria-pressed',on);if(cls==='large-text'&&on)document.documentElement.style.setProperty('--scale','1.18')}}
window.GamesBeyond={get pack(){return pack},runProof:proof,runAccessibility:runAudit,show:view,playBody:openBody,exportHouse};
(async()=>{bind();view('house',false);db=await openDB();if('serviceWorker'in navigator)try{const reg=await navigator.serviceWorker.register(`sw.js?v=${RELEASE}`);reg.update()}catch{}try{await decodePayload()}catch(err){console.error(err);$('status').textContent='HOUSE BUGG';$('status').className='status bad';progress(100,'Load failed: '+err.message);toast('House load failed: '+err.message,true)}})();
})();