(()=>{'use strict';
const $=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)],now=()=>new Date().toISOString();
const DB='jm-games-beyond-public-v03',DBV=1;let db,pack=null,originals=new Map(),currentId=null,currentCategory='all',recent=[];
const req=r=>new Promise((ok,bad)=>{r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)});
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function openDB(){return new Promise((ok,bad)=>{const r=indexedDB.open(DB,DBV);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('edits'))d.createObjectStore('edits',{keyPath:'id'});if(!d.objectStoreNames.contains('revisions')){const s=d.createObjectStore('revisions',{keyPath:'key'});s.createIndex('bodyId','bodyId')}if(!d.objectStoreNames.contains('receipts'))d.createObjectStore('receipts',{keyPath:'key'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
async function all(name){return req(store(name).getAll())}async function get(name,key){return req(store(name).get(key))}async function put(name,val){return req(store(name,'readwrite').put(val))}async function del(name,key){return req(store(name,'readwrite').delete(key))}
function toast(text,bad=false){const e=$('toast');e.textContent=text;e.className='toast show'+(bad?' bad':'');clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='toast',1900)}
function setLoad(pct,text){$('loadPct').textContent=Math.round(pct)+'%';$('loadBar').style.width=pct+'%';$('loadText').textContent=text}
async function sha(textOrBytes){const bytes=typeof textOrBytes==='string'?new TextEncoder().encode(textOrBytes):textOrBytes;const h=await crypto.subtle.digest('SHA-256',bytes);return[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function b64bytes(text){const raw=atob(text),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
async function loadPackage(){setLoad(2,'Opening payload manifest…');const manifest=await fetch('payload-manifest.json?release=0.3.0',{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Manifest HTTP '+r.status);return r.json()});let joined='';for(let i=0;i<manifest.parts;i++){const path=manifest.partPattern.replace('{index:03d}',String(i).padStart(3,'0'));const t=await fetch(path+'?release=0.3.0').then(r=>{if(!r.ok)throw Error(path+' HTTP '+r.status);return r.text()});joined+=t.trim();setLoad(4+(i+1)/manifest.parts*64,`Receiving protected body parts ${i+1}/${manifest.parts}`)}if(joined.length!==manifest.base64Chars)throw Error(`Payload length ${joined.length}/${manifest.base64Chars}`);const bytes=b64bytes(joined),digest=await sha(bytes);if(digest!==manifest.compressedSha256)throw Error('Compressed payload digest mismatch');setLoad(72,'Decompressing the Full House…');let raw=await new Promise((ok,bad)=>LZMA.decompress([...bytes],(result,error)=>error?bad(error):ok(result),p=>setLoad(72+p*19,'Decompressing exact bodies…')));if(typeof raw!=='string')raw=new TextDecoder().decode(Uint8Array.from(raw));if(await sha(raw)!==manifest.rawSha256)throw Error('Full House digest mismatch');setLoad(93,'Parsing passports and source bodies…');const data=JSON.parse(raw);if(!Array.isArray(data.bodies)||data.bodies.length!==manifest.bodyCount)throw Error('Mounted body count mismatch');for(const b of data.bodies){if(!b.html||!/<html|<!doctype/i.test(b.html))throw Error(b.id+' is not an HTML body');originals.set(b.id,structuredClone(b))}const edits=await all('edits');for(const edit of edits){const i=data.bodies.findIndex(b=>b.id===edit.id);if(i>=0)data.bodies[i]={...data.bodies[i],...edit,edited:true}}pack=data;recent=JSON.parse(localStorage.getItem('jm-gb-recent')||'[]');setLoad(100,'15 sovereign rooms mounted. Public House DING.');$('status').textContent='15/15 MOUNTED';$('status').className='status ok';$('enterBtn').disabled=false;await receipt('PUBLIC_HOUSE_BOOT','Games&Beyond',{bodies:data.bodies.length,payloadDigest:manifest.rawSha256,optimisation:manifest.deliveryOptimization});renderAll();return data}
async function receipt(type,body,extra={}){if(!db)return;await put('receipts',{key:Date.now()+Math.random(),time:now(),type,body,extra});renderStats();if(document.querySelector('.view.active')?.dataset.view==='proof')renderReceipts()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
function fmt(n=0){return n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(1)+' MB'}
function bodyCard(b){return`<article class="room ${b.id===currentId?'selected':''}"><h3>${esc(b.name)} <span>${esc(b.version||'')}</span></h3><p>${esc(b.role||'Sovereign mounted body')}</p><div class="tags"><span class="tag">${esc(b.category||'Room')}</span><span class="tag live">MOUNTED</span><span class="tag">${fmt(new Blob([b.html]).size)}</span>${b.edited?'<span class="tag live">CREATOR REVISION</span>':''}</div><div class="roomActions"><button data-play="${b.id}">PLAY BODY</button><button data-edit="${b.id}">EDIT</button><button data-export="${b.id}">EXPORT</button></div></article>`}
function filtered(){if(!pack)return[];const term=($('search')?.value||'').toLowerCase();return pack.bodies.filter(b=>(currentCategory==='all'||b.category===currentCategory)&&(!term||[b.id,b.name,b.version,b.role,b.category].join(' ').toLowerCase().includes(term)))}
function renderRooms(){const rows=filtered();$('roomRail').innerHTML=rows.length?rows.map(bodyCard).join(''):'<div class="empty">No rooms match that route.</div>';bindCards()}
function renderRecent(){if(!pack)return;const rows=recent.map(id=>pack.bodies.find(b=>b.id===id)).filter(Boolean).slice(0,5);$('recentRooms').innerHTML=rows.length?rows.map(bodyCard).join(''):'<div class="empty">Open a room and the House will remember the route.</div>';bindCards()}
function renderFilters(){if(!pack)return;const cats=['all',...new Set(pack.bodies.map(b=>b.category))];$('filters').innerHTML=cats.map(c=>`<button class="filter ${c==='all'?'active':''}" data-cat="${esc(c)}">${c==='all'?'ALL ROOMS':esc(c)}</button>`).join('');qa('[data-cat]').forEach(x=>x.onclick=()=>{currentCategory=x.dataset.cat;qa('[data-cat]').forEach(y=>y.classList.toggle('active',y===x));renderRooms()})}
async function renderStats(){if(!pack)return;$('mountedStat').textContent=pack.bodies.length;$('editedStat').textContent=(await all('edits')).length;$('receiptStat').textContent=(await all('receipts')).length}
function bindCards(){qa('[data-play]').forEach(x=>x.onclick=()=>playBody(x.dataset.play));qa('[data-edit]').forEach(x=>x.onclick=()=>openEdit(x.dataset.edit));qa('[data-export]').forEach(x=>x.onclick=()=>exportOne(x.dataset.export))}
function body(id){return pack?.bodies.find(b=>b.id===id)}
function recordRecent(id){recent=[id,...recent.filter(x=>x!==id)].slice(0,8);localStorage.setItem('jm-gb-recent',JSON.stringify(recent));renderRecent()}
async function playBody(id,htmlOverride=null){const b=body(id);if(!b)return toast('Room unavailable',true);recordRecent(id);const html=htmlOverride??b.html,url=URL.createObjectURL(new Blob([html],{type:'text/html'}));const w=window.open(url,'_blank');if(!w){const a=document.createElement('a');a.href=url;a.target='_blank';a.rel='noopener';a.textContent='OPEN '+b.name;a.style.display='none';document.body.append(a);a.click();a.remove();toast('Popup blocked: browser may ask permission.',true)}else toast(b.name+' opened as its own body');setTimeout(()=>URL.revokeObjectURL(url),120000);await receipt('BODY_OPENED',b.name,{id,edited:Boolean(b.edited)})}
function show(name){qa('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));qa('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));scrollTo({top:0,behavior:'smooth'});if(name==='rooms')renderRooms();if(name==='proof')renderReceipts()}
function openEdit(id){const b=body(id);if(!b)return;currentId=id;$('editEmpty').hidden=true;$('workspace').hidden=false;$('bodyName').value=b.name;$('bodyVersion').value=b.version||'';$('bodyRole').value=b.role||'';$('bodyCategory').value=b.category||'';$('bodyStage').value=b.stage||'';$('source').value=b.html;$('bodyState').textContent=`${b.edited?'CREATOR REVISION':'PROTECTED DELIVERY SOURCE'} · ${b.hash?.slice(0,18)||'unhashed'}… · ${fmt(new Blob([b.html]).size)}`;show('edit')}
async function savePassport(){const b=body(currentId);if(!b)return;Object.assign(b,{name:$('bodyName').value.trim()||b.name,version:$('bodyVersion').value.trim(),role:$('bodyRole').value.trim(),category:$('bodyCategory').value.trim(),stage:$('bodyStage').value.trim(),edited:true,updatedAt:now()});await saveEdit(b,'PASSPORT_UPDATED');toast('Body passport saved')}
async function saveEdit(b,type='SOURCE_REVISION_SAVED'){const prev=await get('edits',b.id)||originals.get(b.id);await put('revisions',{key:Date.now()+Math.random(),bodyId:b.id,time:now(),html:prev.html,passport:{name:prev.name,version:prev.version,role:prev.role,category:prev.category,stage:prev.stage}});b.hash=await sha(b.html);b.size=new Blob([b.html]).size;b.edited=true;await put('edits',structuredClone(b));await receipt(type,b.name,{id:b.id,hash:b.hash,bytes:b.size});renderAll();openEdit(b.id)}
async function saveSource(){const b=body(currentId);if(!b)return;const html=$('source').value;if(!/<html|<!doctype/i.test(html))return toast('Source is not a complete HTML body',true);b.html=html;await saveEdit(b);toast('Source revision saved')}
async function undoSource(){const b=body(currentId);if(!b)return;const rows=(await all('revisions')).filter(r=>r.bodyId===b.id).sort((a,z)=>z.key-a.key);if(!rows.length)return toast('No earlier revision',true);const r=rows[0];b.html=r.html;Object.assign(b,r.passport||{});await del('revisions',r.key);await put('edits',{...structuredClone(b),edited:true,hash:await sha(b.html),size:new Blob([b.html]).size});await receipt('SOURCE_UNDO',b.name,{from:r.time});renderAll();openEdit(b.id);toast('Previous revision restored')}
async function restoreBody(){const orig=originals.get(currentId);if(!orig)return;const i=pack.bodies.findIndex(b=>b.id===currentId);pack.bodies[i]=structuredClone(orig);await del('edits',currentId);await receipt('PROTECTED_SOURCE_RESTORED',orig.name,{id:orig.id});renderAll();openEdit(orig.id);toast('Protected delivery source restored')}
function download(name,text,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
async function exportOne(id){const b=body(id);if(!b)return;download((b.sourceName||b.id+'.html').split('/').pop(),b.html,'text/html');await receipt('BODY_EXPORTED',b.name,{id,hash:b.hash,bytes:new Blob([b.html]).size});toast('Editable body exported')}
async function runProof(){if(!pack)return;const results=[];for(const b of pack.bodies){const digest=await sha(b.html);results.push({id:b.id,name:b.name,html:/<html|<!doctype/i.test(b.html),bytes:new Blob([b.html]).size,declaredHash:b.hash,digest,edited:Boolean(b.edited),pass:/<html|<!doctype/i.test(b.html)&&Boolean(b.html)})}const pass=results.length===15&&results.every(r=>r.pass);const report={schema:'JM.GamesBeyond.PublicProof/0.3',checkedAt:now(),pass,bodyCount:results.length,edited:results.filter(r=>r.edited).length,results};$('proofBox').textContent=JSON.stringify(report,null,2);await receipt('PUBLIC_HOUSE_PROOF',pass?'DING':'BUGG',{pass,bodyCount:results.length});toast(pass?'15-room House proof DING':'House proof found a gap',!pass);show('proof');return report}
async function exportHouse(){const payload={...pack,schema:'JM.GamesBeyondHouse/0.3-public-export',exportedAt:now(),full:true,bodies:pack.bodies,localReceipts:await all('receipts')};download('GAMES_BEYOND_FULL_HOUSE_v0_3_LOCAL_EXPORT.json',JSON.stringify(payload,null,2),'application/json');await receipt('FULL_HOUSE_EXPORTED','Games&Beyond',{bodies:pack.bodies.length,edited:pack.bodies.filter(b=>b.edited).length});toast('Full local House exported')}
async function importHouse(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.bodies))throw Error('No bodies array');for(const incoming of data.bodies){const b=body(incoming.id);if(b&&incoming.html){Object.assign(b,incoming,{edited:true});await put('edits',structuredClone(b))}}await receipt('HOUSE_BACKUP_IMPORTED','Games&Beyond',{bodies:data.bodies.length});renderAll();toast('House backup imported')}catch(e){toast('Import failed: '+e.message,true)}}
async function clearEdits(){if(!confirm('Clear every local body edit and return to the protected public delivery bodies?'))return;for(const e of await all('edits'))await del('edits',e.id);for(const [id,orig] of originals){const i=pack.bodies.findIndex(b=>b.id===id);if(i>=0)pack.bodies[i]=structuredClone(orig)}await receipt('ALL_LOCAL_EDITS_CLEARED','Games&Beyond',{});renderAll();toast('All rooms restored')}
async function renderReceipts(){if(!db)return;const rows=(await all('receipts')).sort((a,b)=>b.key-a.key).slice(0,120);$('receipts').innerHTML=rows.map(r=>`<div class="receipt"><b>${esc(r.type)} · ${esc(r.body)}</b><span>${esc(r.time)}\n${esc(JSON.stringify(r.extra||{}))}</span></div>`).join('')||'<div class="empty">No receipts yet.</div>'}
function renderAll(){renderFilters();renderRooms();renderRecent();renderStats();if(currentId&&body(currentId))openEdit(currentId)}
function bind(){qa('.nav button').forEach(x=>x.onclick=()=>show(x.dataset.view));$('enterBtn').onclick=()=>show('rooms');$('reloadBtn').onclick=()=>location.reload();$('search').oninput=renderRooms;$('proofQuick').onclick=$('runProof').onclick=runProof;$('savePassport').onclick=savePassport;$('saveSource').onclick=saveSource;$('undoSource').onclick=undoSource;$('restoreBody').onclick=restoreBody;$('exportBody').onclick=()=>exportOne(currentId);$('testSource').onclick=()=>playBody(currentId,$('source').value);$('exportHouse').onclick=exportHouse;$('importHouse').onclick=()=>$('importFile').click();$('importFile').onchange=e=>{if(e.target.files[0])importHouse(e.target.files[0]);e.target.value=''};$('clearEdits').onclick=clearEdits;window.addEventListener('keydown',e=>{if(e.key==='Escape')show('rooms')})}
async function init(){bind();db=await openDB();if('serviceWorker'in navigator){try{const reg=await navigator.serviceWorker.register('sw.js?v=0.3.0');reg.update()}catch{}}try{await loadPackage()}catch(e){console.error(e);$('status').textContent='HOUSE BUGG';$('status').className='status bad';setLoad(100,'Load failed: '+e.message);toast('House load failed: '+e.message,true)}}
window.GamesBeyond={get pack(){return pack},runProof,show,playBody,exportHouse};init();
})();
