(()=>{'use strict';
const $=id=>document.getElementById(id),qa=s=>[...document.querySelectorAll(s)],now=()=>new Date().toISOString();
const DB_NAME='games-beyond-house',DB_VERSION=2,MANIFEST_URL='bundled-bodies.json';
const CATEGORIES=['Playable Games','Engines & Creator Hubs','Loops & Reusable Organs','Benchmarks & Recovery','Host Shelf','Governance & Receipts'];
let db,manifest={bundled:[],sourceTransferQueue:[]},currentId=null,currentRoomId=null,currentCategory='all',currentStage='all',deferredInstall=null;
const req=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
function transaction(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
const all=name=>req(transaction(name).getAll());const get=(name,key)=>req(transaction(name).get(key));const put=(name,value)=>req(transaction(name,'readwrite').put(value));const add=(name,value)=>req(transaction(name,'readwrite').add(value));const del=(name,key)=>req(transaction(name,'readwrite').delete(key));
function openDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('bodies'))d.createObjectStore('bodies',{keyPath:'id'});if(!d.objectStoreNames.contains('receipts'))d.createObjectStore('receipts',{keyPath:'id',autoIncrement:true});if(!d.objectStoreNames.contains('revisions')){const s=d.createObjectStore('revisions',{keyPath:'id',autoIncrement:true});s.createIndex('bodyId','bodyId')}if(!d.objectStoreNames.contains('settings'))d.createObjectStore('settings',{keyPath:'key'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function hashText(text){if(globalThis.crypto?.subtle){const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join('')}let h=2166136261;for(let i=0;i<text.length;i++){h^=text.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(16)}
function normalize(s=''){return String(s).toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function formatBytes(n=0){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(1)+' MB'}
function toast(text,bad=false){const e=$('toast');e.textContent=text;e.className='toast show'+(bad?' bad':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.className='toast',1600)}
async function receipt(type,body,extra={}){await add('receipts',{time:now(),type,body,extra});renderStats();if(document.querySelector('.view.active')?.dataset.view==='proof')renderReceipts()}
async function loadManifest(){const response=await fetch(MANIFEST_URL,{cache:'no-store'});if(!response.ok)throw Error('Bundled manifest unavailable: HTTP '+response.status);manifest=await response.json();if(!Array.isArray(manifest.bundled))throw Error('Bundled manifest is invalid');return manifest}
async function seedRegistry(){for(const entry of manifest.bundled){const old=await get('bodies',entry.id);if(!old)await put('bodies',{...entry,mounted:false,bundled:true,bundlePath:entry.path,bundleState:'NOT-FETCHED',status:'BUNDLED',html:'',hash:'',size:0,sourceName:entry.path,userModified:false,updatedAt:now()});else await put('bodies',{...old,name:old.name||entry.name,version:old.version||entry.version,category:old.category||entry.category,role:old.role||entry.role,stage:old.stage||entry.stage,bundled:true,bundlePath:entry.path,declaredRoutes:entry.routes||old.declaredRoutes||[],sourceStatus:entry.sourceStatus||old.sourceStatus})}
for(const entry of manifest.sourceTransferQueue||[]){const old=await get('bodies',entry.id);if(!old)await put('bodies',{id:entry.id,name:entry.name,version:entry.version||'source selection',category:queueCategory(entry.id),role:queueRole(entry.id),stage:entry.id==='jm-studios'?'RECOVERY':'REGISTERED',mounted:false,bundled:false,bundleState:'SOURCE-TRANSFER',status:'SOURCE-TRANSFER',html:'',hash:'',size:0,sourceName:'',sourceFileId:entry.sourceFileId||'',sourceStatus:entry.status,aliases:[],updatedAt:now()});else if(!old.mounted)await put('bodies',{...old,sourceFileId:entry.sourceFileId||old.sourceFileId,sourceStatus:entry.status,bundleState:'SOURCE-TRANSFER'})}
if(!(await all('receipts')).length)await receipt('HOUSE_V0_2_GENESIS','Games&Beyond',{bundled:manifest.bundled.length,transferQueue:(manifest.sourceTransferQueue||[]).length})}
function queueCategory(id){if(['gameforge','glyphplay','glyphforge','game-native-core','gamecore','playform'].includes(id))return'Engines & Creator Hubs';if(['combound'].includes(id))return'Loops & Reusable Organs';if(['quadze'].includes(id))return'Benchmarks & Recovery';if(id==='jm-studios')return'Host Shelf';return'Playable Games'}
function queueRole(id){const roles={fourfold-arena:'Living-body competitive arena / active flagship route','tboys-core-clash':'T-Boys tactical crew clash game','rim-route':'Portrait basketball / live dribble and ball contact','crewbound-arena':'Signature powers / living field arena','house-siege':'Aim parity / focus-depth house battle','western-sniper':'Identity-field live duel','dead-reckon':'Dual-aim body / split-hand route',cardbored:'Card-board game body / LG future-position route',gameforge:'Game-first production forge / one-player separation',glyphplay:'Creator-first playable logic engine',glyphforge:'ProjectBody to connected play-test bridge','game-native-core':'Native core / apps and tools bridge',gamecore:'Shared game room and donor-estate integration body',playform:'Game-form and creator-system body',combound:'Natural combo kinetics / combat donor organ',quadze:'Frozen benchmark / control donor / multi-hub authority','jm-studios':'Separate host shelf awaiting verified working body'};return roles[id]||'Source body awaiting exact transfer'}
async function saveRevision(body,reason){if(!body?.html)return;await add('revisions',{bodyId:body.id,time:now(),reason,html:body.html,hash:body.hash});const tx=db.transaction('revisions','readwrite'),store=tx.objectStore('revisions'),items=await req(store.index('bodyId').getAll(IDBKeyRange.only(body.id)));items.sort((a,b)=>b.id-a.id);for(const item of items.slice(8))store.delete(item.id)}
async function fetchBundle(entry,{force=false}={}){const response=await fetch(entry.path,{cache:'no-store'});if(!response.ok)throw Error(`${entry.name}: HTTP ${response.status}`);const html=await response.text();if(!/<html|<!doctype/i.test(html))throw Error(entry.name+': fetched file is not an HTML body');const hash=await hashText(html),size=new Blob([html]).size;let body=await get('bodies',entry.id);if(!body)body={...entry,id:entry.id};
if(body.mounted&&body.userModified&&!force&&body.hash!==hash){body.bundleState='UPDATE-AVAILABLE';body.availableBundleHash=hash;body.availableBundleSize=size;body.availableBundleVersion=entry.version;body.availableBundlePath=entry.path;await put('bodies',body);return{body,state:'UPDATE-AVAILABLE'}}
if(body.mounted&&body.hash===hash){body.bundleState='CURRENT';body.bundled=true;body.bundlePath=entry.path;body.bundleHash=hash;await put('bodies',body);return{body,state:'CURRENT'}}
if(body.mounted&&body.html)await saveRevision(body,'BUNDLE_UPDATE');
body={...body,...entry,mounted:true,bundled:true,bundlePath:entry.path,bundleHash:hash,bundleState:'CURRENT',status:'MOUNTED',html,hash,size,sourceName:entry.path,userModified:false,updatedAt:now()};await put('bodies',body);await receipt(body.hash?'BUNDLED_BODY_MOUNTED':'BUNDLE_ERROR',entry.name,{path:entry.path,bytes:size,hash});return{body,state:'MOUNTED'}}
async function mountAllBundles({force=false,quiet=false}={}){let mounted=0,current=0,updates=0,failed=[];for(const entry of manifest.bundled){try{const result=await fetchBundle(entry,{force});if(result.state==='MOUNTED')mounted++;else if(result.state==='CURRENT')current++;else if(result.state==='UPDATE-AVAILABLE')updates++}catch(error){failed.push({id:entry.id,error:error.message});let body=await get('bodies',entry.id);if(body){body.bundleState='FETCH-FAILED';body.lastBundleError=error.message;await put('bodies',body)}await receipt('BUNDLE_FETCH_FAILED',entry.name,{path:entry.path,error:error.message})}}
await renderAll();if(!quiet)toast(failed.length?`${mounted+current} bodies ready; ${failed.length} failed verification`:`${mounted+current} bundled bodies mounted`,Boolean(failed.length));return{mounted,current,updates,failed}}
async function findMatch(filename,text){const title=text.match(/<title[^>]*>([^<]+)/i)?.[1]||'',needle=normalize(filename+' '+title),bodies=await all('bodies');let best=null,score=0;for(const body of bodies){for(const value of [body.id,body.name,...(body.aliases||[])]){const candidate=normalize(value);if(candidate&&needle.includes(candidate)&&candidate.length>score){best=body;score=candidate.length}}}return score>=4?best:null}
async function mountLocalFiles(files,replaceId=null){for(const file of files){if(!/\.html?$/i.test(file.name)&&!file.type.includes('html')){toast(file.name+' is not HTML',true);continue}const html=await file.text();let body=replaceId?await get('bodies',replaceId):await findMatch(file.name,html);if(!body){const title=html.match(/<title[^>]*>([^<]+)/i)?.[1]?.trim()||file.name.replace(/\.html?$/i,'');body={id:normalize(title).replace(/ /g,'-')+'-'+Date.now().toString(36),name:title,version:'unclassified',category:'Benchmarks & Recovery',role:'New mounted body — passport review required',stage:'MOUNTED',aliases:[]}}if(body.html)await saveRevision(body,'LOCAL_REPLACE');const hash=await hashText(html);body={...body,mounted:true,status:'MOUNTED',html,hash,size:new Blob([html]).size,sourceName:file.name,userModified:true,bundleState:body.bundled&&body.bundleHash!==hash?'CUSTOM':'LOCAL',updatedAt:now()};if(body.stage==='REGISTERED')body.stage='MOUNTED';await put('bodies',body);await receipt('LOCAL_BODY_MOUNTED',body.name,{file:file.name,bytes:body.size,hash});currentId=body.id}await renderAll();toast(files.length+' local body file(s) mounted')}
function bodyState(body){if(body.bundleState==='UPDATE-AVAILABLE')return'UPDATE';if(body.bundleState==='FETCH-FAILED')return'BUGG';if(body.mounted)return'MOUNTED';if(body.bundled)return'BUNDLED';if(body.bundleState==='SOURCE-TRANSFER')return'TRANSFER';return'REGISTERED'}
function badgeClass(value){return value==='MOUNTED'?'mounted':value==='BUNDLED'||value==='FROZEN'?'ready':value==='UPDATE'?'update':value==='BUGG'?'bad':'recovery'}
function card(body){const state=bodyState(body),open=body.mounted?`<button data-open="${body.id}">OPEN BODY</button><button data-route="edit" data-id="${body.id}">EDIT</button><button data-route="source" data-id="${body.id}">SOURCE</button>`:body.bundled?`<button class="mount" data-fetch="${body.id}">FETCH BODY</button><button data-select="${body.id}">PASSPORT</button><button data-status="${body.id}">STATUS</button>`:`<button data-select="${body.id}">PASSPORT</button><button data-status="${body.id}">CUSTODY</button><button class="mount" data-local="${body.id}">MOUNT FILE</button>`;return`<article class="body-card ${body.id===currentId?'selected':''}"><div class="body-top"><div><h3>${esc(body.name)} <span>${esc(body.version||'')}</span></h3><p>${esc(body.role||'Unclassified body')}</p></div><button class="select" data-select="${body.id}" aria-label="Edit passport">✎</button></div><div class="passport"><span>${esc(body.category)}</span><span class="${badgeClass(body.stage)}">${esc(body.stage||'REGISTERED')}</span><span class="${badgeClass(state)}">${state}</span>${body.size?`<span>${formatBytes(body.size)}</span>`:''}</div>${body.sourceStatus&&!body.mounted?`<div class="custody">${esc(body.sourceStatus)}</div>`:''}<div class="body-actions">${open}</div></article>`}
async function filteredBodies(){let list=await all('bodies'),term=normalize($('searchInput')?.value||'');return list.filter(b=>(currentCategory==='all'||b.category===currentCategory)&&(currentStage==='all'||b.stage===currentStage)&&(!term||normalize([b.id,b.name,b.version,b.role,b.category,b.stage,b.sourceStatus].join(' ')).includes(term))).sort((a,b)=>Number(b.mounted)-Number(a.mounted)||Number(b.bundled)-Number(a.bundled)||a.category.localeCompare(b.category)||a.name.localeCompare(b.name))}
async function renderBodies(){const list=await filteredBodies();$('bodyList').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No bodies match this corridor.</div>';bindCards()}
async function renderRecent(){const list=(await all('bodies')).filter(b=>b.mounted).sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')).slice(0,6);$('recentList').innerHTML=list.length?list.map(card).join(''):'<div class="empty">No body has passed the mount gate yet.</div>';bindCards()}
async function renderStats(){const bodies=await all('bodies'),receipts=await all('receipts');$('statRegistered').textContent=bodies.length;$('statBundled').textContent=bodies.filter(b=>b.bundled).length;$('statMounted').textContent=bodies.filter(b=>b.mounted).length;$('statReceipts').textContent=receipts.length;const transfer=bodies.filter(b=>bodyState(b)==='TRANSFER').length;$('transferCount').textContent=transfer;$('bundleCount').textContent=manifest.bundled.length}
async function renderReceipts(){const rows=(await all('receipts')).sort((a,b)=>b.id-a.id).slice(0,200);$('receiptList').innerHTML=rows.length?rows.map(r=>`<div class="receipt"><b>${esc(r.type)} · ${esc(r.body)}</b><span>${esc(r.time)}\n${esc(JSON.stringify(r.extra||{}))}</span></div>`).join(''):'<div class="empty">No receipts yet.</div>'}
async function renderAll(){await Promise.all([renderStats(),renderBodies(),renderRecent(),renderReceipts()]);if(currentId)loadWorkbench(currentId)}
function bindCards(){qa('[data-open]').forEach(x=>x.onclick=()=>openRoom(x.dataset.open,'play'));qa('[data-route]').forEach(x=>x.onclick=()=>openRoom(x.dataset.id,x.dataset.route));qa('[data-select],.select').forEach(x=>x.onclick=()=>{currentId=x.dataset.select;show('edit');loadWorkbench(currentId)});qa('[data-fetch]').forEach(x=>x.onclick=async()=>{const entry=manifest.bundled.find(b=>b.id===x.dataset.fetch);if(entry){await fetchBundle(entry);await renderAll();toast(entry.name+' mounted')}});qa('[data-local]').forEach(x=>x.onclick=()=>{currentId=x.dataset.local;$('bodyFiles').click()});qa('[data-status]').forEach(x=>x.onclick=async()=>{const b=await get('bodies',x.dataset.status);toast(b.sourceStatus||`${b.name} is ${bodyState(b)}.`)})}
function renderFilters(){$('categoryFilters').innerHTML=['all',...CATEGORIES].map(c=>`<button class="filter ${c==='all'?'active':''}" data-category="${esc(c)}">${c==='all'?'ALL ROOMS':esc(c)}</button>`).join('');qa('[data-category]').forEach(x=>x.onclick=()=>{currentCategory=x.dataset.category;qa('[data-category]').forEach(y=>y.classList.toggle('active',x===y));renderBodies()})}
async function loadWorkbench(id){const b=await get('bodies',id);if(!b)return;$('workEmpty').classList.add('hidden');$('workContent').classList.remove('hidden');$('editName').value=b.name;$('editVersion').value=b.version||'';$('editRole').value=b.role||'';$('editCategory').value=b.category;$('editStage').value=b.stage||'REGISTERED';$('sourceEditor').value=b.html||'';$('sourceEditor').disabled=!b.mounted;for(const id of['saveSource','undoSource','testSource','exportBody'])$(id).disabled=!b.mounted;$('workStatus').innerHTML=`<strong>${bodyState(b)}</strong> · ${esc(b.sourceName||b.sourceStatus||'No source body mounted')} ${b.hash?'· '+esc(b.hash.slice(0,18))+'…':''}`;$('applyBundleUpdate').classList.toggle('hidden',b.bundleState!=='UPDATE-AVAILABLE')}
async function savePassport(){if(!currentId)return toast('Select a body first',true);const b=await get('bodies',currentId);Object.assign(b,{name:$('editName').value.trim()||b.name,version:$('editVersion').value.trim(),role:$('editRole').value.trim(),category:$('editCategory').value,stage:$('editStage').value,userModified:true,updatedAt:now()});await put('bodies',b);await receipt('PASSPORT_UPDATED',b.name,{version:b.version,category:b.category,stage:b.stage});toast('Passport saved');renderAll()}
async function saveSource(){const b=await get('bodies',currentId);if(!b?.mounted)return toast('Mount the exact body first',true);const html=$('sourceEditor').value;if(!html.trim())return toast('Source cannot be empty',true);await saveRevision(b,'SOURCE_EDIT');b.html=html;b.hash=await hashText(html);b.size=new Blob([html]).size;b.userModified=true;b.bundleState=b.bundled?'CUSTOM':'LOCAL';b.updatedAt=now();await put('bodies',b);await receipt('SOURCE_REVISION_SAVED',b.name,{bytes:b.size,hash:b.hash});toast('Exact source revision saved');renderAll()}
async function undoSource(){const tx=db.transaction('revisions','readonly'),items=await req(tx.objectStore('revisions').index('bodyId').getAll(IDBKeyRange.only(currentId)));if(!items.length)return toast('No recovery revision available',true);items.sort((a,b)=>b.id-a.id);const rev=items[0],b=await get('bodies',currentId);await saveRevision(b,'UNDO_BACKUP');b.html=rev.html;b.hash=await hashText(rev.html);b.size=new Blob([rev.html]).size;b.userModified=true;b.updatedAt=now();await put('bodies',b);await del('revisions',rev.id);await receipt('SOURCE_UNDO',b.name,{restoredFrom:rev.time});$('sourceEditor').value=b.html;toast('Previous revision restored')}
async function applyBundleUpdate(){const b=await get('bodies',currentId),entry=manifest.bundled.find(x=>x.id===currentId);if(!b||!entry)return;await saveRevision(b,'PRE_BUNDLE_UPDATE');const result=await fetchBundle(entry,{force:true});await receipt('BUNDLE_UPDATE_APPLIED',entry.name,{state:result.state});toast('Bundle update applied; previous source remains recoverable');renderAll()}
function blobURL(html){return URL.createObjectURL(new Blob([html],{type:'text/html'}))}
async function openRoom(id,route='play'){const b=await get('bodies',id);if(!b?.mounted)return toast('This body is not mounted. No fake door opened.',true);currentRoomId=id;$('roomName').textContent=b.name+' '+(b.version||'');$('roomStatus').textContent=`${b.stage} · ${formatBytes(b.size)} · ${b.userModified?'CREATOR REVISION':'BUNDLED SOURCE'}`;$('roomModal').classList.add('open');$('roomModal').setAttribute('aria-hidden','false');$('roomFrame').srcdoc=b.html;qa('.room-actions [data-room-route]').forEach(x=>x.classList.toggle('active',x.dataset.roomRoute===route));$('roomFrame').onload=()=>{if(route!=='play')setTimeout(()=>routeInside(route),140)};await receipt('BODY_OPENED',b.name,{route})}
function routeInside(route){let doc;try{doc=$('roomFrame').contentDocument}catch(_){doc=null}if(!doc)return toast('Body opened; route inspection is unavailable.',true);const terms={edit:['edit','tune','create','workbench','builder','author'],logic:['logic','route','rules','changebox','jm logic'],source:['source','code','project body','json'],proof:['proof','trace','receipt','qa','test']}[route]||[route],items=[...doc.querySelectorAll('button,a,[role="button"],[data-tab],[data-view]')],hit=items.find(el=>terms.some(term=>(el.textContent||'').trim().toLowerCase().includes(term)));if(hit){hit.click();toast(route.toUpperCase()+' corridor reached inside '+$('roomName').textContent)}else toast('Body is open. No host-detectable '+route+' control; use its own internal controls.',true)}
async function openExternal(){const b=await get('bodies',currentRoomId);if(!b?.mounted)return;const w=window.open('about:blank','_blank');if(!w)return toast('Popup blocked',true);const url=blobURL(b.html);w.location=url;setTimeout(()=>URL.revokeObjectURL(url),60000);await receipt('BODY_OPENED_EXTERNAL',b.name)}
async function testCopy(){const b=await get('bodies',currentId);if(!b?.mounted)return;const w=window.open('about:blank','_blank');if(!w)return toast('Popup blocked',true);const url=blobURL($('sourceEditor').value);w.location=url;setTimeout(()=>URL.revokeObjectURL(url),60000);await receipt('UNSAVED_TEST_COPY_OPENED',b.name)}
function download(name,text,type='application/octet-stream'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
async function exportBody(){const b=await get('bodies',currentId);if(!b?.mounted)return toast('Body not mounted',true);download((b.sourceName||b.id+'.html').split('/').pop().replace(/[^a-z0-9._-]+/gi,'_'),b.html,'text/html');await receipt('BODY_EXPORTED',b.name,{hash:b.hash,bytes:b.size});toast('Exact mounted body exported')}
async function exportHouse(full=false){const bodies=await all('bodies'),receipts=await all('receipts'),revisions=full?await all('revisions'):[];const payload={schema:'JM.GamesBeyondHouse/0.2',name:'Games&Beyond — The JM Games House',exportedAt:now(),full,law:'One front door. Many sovereign game rooms.',bundledManifest:manifest,bodies:bodies.map(b=>full?b:{...b,html:undefined}),receipts,revisions:full?revisions:undefined,android:{status:'route-ready-not-compiled',compiledApk:false}};download(full?'games_beyond_full_house_v0_2.json':'games_beyond_registry_v0_2.json',JSON.stringify(payload,null,2),'application/json');await receipt(full?'FULL_HOUSE_EXPORTED':'REGISTRY_EXPORTED','Games&Beyond',{bodies:bodies.length,mounted:bodies.filter(b=>b.mounted).length});toast(full?'Full editable House exported':'Registry exported')}
async function importHouse(file){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.bodies))throw Error('No bodies array');for(const b of data.bodies)await put('bodies',{...b,html:b.html||'',mounted:Boolean(b.mounted&&b.html)});for(const r of data.receipts||[])await add('receipts',{time:r.time||now(),type:r.type||'IMPORTED_RECEIPT',body:r.body||'Imported',extra:r.extra||{}});await receipt('HOUSE_BACKUP_IMPORTED','Games&Beyond',{bodies:data.bodies.length,full:Boolean(data.full)});toast('House backup imported');renderAll()}catch(error){toast('Import failed: '+error.message,true)}}
async function verifyHouse(){const results=[];for(const entry of manifest.bundled){try{const response=await fetch(entry.path,{cache:'no-store'}),html=await response.text(),body=await get('bodies',entry.id);results.push({id:entry.id,path:entry.path,http:response.status,html:/<html|<!doctype/i.test(html),mounted:Boolean(body?.mounted),hashMatch:Boolean(body?.hash&&(await hashText(html))===body.hash),pass:response.ok&&/<html|<!doctype/i.test(html)&&Boolean(body?.mounted)})}catch(error){results.push({id:entry.id,path:entry.path,pass:false,error:error.message})}}const pass=results.every(x=>x.pass);await receipt('HOUSE_BUNDLE_PROOF',pass?'DING':'BUGG',{pass,results});$('proofResults').textContent=JSON.stringify({pass,checkedAt:now(),results},null,2);toast(pass?'Bundled House proof DING':'House proof found a gap',!pass);return{pass,results}}
function show(name){qa('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));qa('.nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));scrollTo({top:0,behavior:'smooth'});if(name==='rooms')renderBodies();if(name==='proof')renderReceipts()}
function bindStatic(){qa('.nav button').forEach(x=>x.onclick=()=>show(x.dataset.view));$('mountAll').onclick=()=>mountAllBundles();$('mountHero').onclick=()=>mountAllBundles();$('quickMount').onclick=$('mountLocal').onclick=()=>{currentId=null;$('bodyFiles').click()};$('openRooms').onclick=$('showAll').onclick=()=>show('rooms');$('searchInput').oninput=renderBodies;$('stageFilter').onchange=e=>{currentStage=e.target.value;renderBodies()};$('bodyFiles').onchange=e=>{const files=[...e.target.files],replace=currentId&&files.length===1?currentId:null;mountLocalFiles(files,replace);e.target.value=''};$('replaceFile').onchange=e=>{if(e.target.files[0])mountLocalFiles([e.target.files[0]],currentId);e.target.value=''};$('replaceBody').onclick=()=>{if(!currentId)return toast('Select a body',true);$('replaceFile').click()};$('savePassport').onclick=savePassport;$('saveSource').onclick=saveSource;$('undoSource').onclick=undoSource;$('testSource').onclick=testCopy;$('exportBody').onclick=exportBody;$('applyBundleUpdate').onclick=applyBundleUpdate;$('verifyHouse').onclick=verifyHouse;$('exportRegistry').onclick=()=>exportHouse(false);$('exportFull').onclick=()=>exportHouse(true);$('exportReceipts').onclick=async()=>download('games_beyond_receipts_v0_2.json',JSON.stringify(await all('receipts'),null,2),'application/json');$('importHouse').onclick=()=>$('houseFile').click();$('houseFile').onchange=e=>{if(e.target.files[0])importHouse(e.target.files[0]);e.target.value=''};$('closeRoom').onclick=()=>{$('roomModal').classList.remove('open');$('roomModal').setAttribute('aria-hidden','true');$('roomFrame').srcdoc='';currentRoomId=null};$('openExternal').onclick=openExternal;qa('.room-actions [data-room-route]').forEach(x=>x.onclick=()=>{qa('.room-actions [data-room-route]').forEach(y=>y.classList.toggle('active',x===y));routeInside(x.dataset.roomRoute)});qa('.corridor').forEach(x=>x.onclick=()=>{currentCategory=x.dataset.filter;show('rooms');qa('[data-category]').forEach(y=>y.classList.toggle('active',y.dataset.category===currentCategory));renderBodies()});$('contrastToggle').onchange=async e=>{document.documentElement.classList.toggle('high-contrast',e.target.checked);await put('settings',{key:'contrast',value:e.target.checked})};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;$('installBtn').classList.add('green')});$('installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null}else toast('Use browser menu → Install app / Add to Home screen')};window.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('roomModal').classList.contains('open'))$('closeRoom').click()})}
async function init(){db=await openDB();await loadManifest();await seedRegistry();renderFilters();for(const category of CATEGORIES)$('editCategory').append(new Option(category,category));const contrast=await get('settings','contrast');$('contrastToggle').checked=Boolean(contrast?.value);document.documentElement.classList.toggle('high-contrast',Boolean(contrast?.value));bindStatic();await mountAllBundles({quiet:true});await renderAll();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});await receipt('HOUSE_BOOT','Games&Beyond',{version:'0.2',bundled:manifest.bundled.length,mounted:(await all('bodies')).filter(b=>b.mounted).length})}
window.GamesBeyondHouse={version:'0.2',get manifest(){return manifest},get db(){return db},mountAllBundles,verifyHouse,openRoom,show,exportHouse};
init().catch(error=>{console.error(error);toast('House boot error: '+error.message,true);$('bootStatus').textContent='BUGG · '+error.message});
})();