import{AuthorityHoldEngineV2,signReceipt,verifyReceipt}from'./core/engine.mjs';
const $=id=>document.getElementById(id),engine=new AuthorityHoldEngineV2();let signed=null,replayEnvelope=null;
const val=id=>$(id).value,num=id=>Number(val(id)||0),checked=id=>$(id).checked;
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function room(name){document.querySelectorAll('.room').forEach(x=>x.classList.toggle('active',x.id===name));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.room===name))}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>room(b.dataset.room));
function packet(){return{issuer:val('issuer'),receiver:val('receiver'),subject:val('subject'),action:val('action'),directive:val('directive'),scope:val('scope'),channel:val('channel'),authorityRank:num('authority'),boundaryRank:num('boundary'),durationMinutes:num('duration'),releaseKey:val('releaseKey'),sourceVerified:checked('sourceVerified'),antiOverride:checked('antiOverride')}}
function currentTarget(){return val('target')||[...engine.instructions.keys()][0]||''}
function render(){
  const q=engine.effectiveGovernance(val('queryScope')||'root',val('querySubject')),$status=$('status');$status.textContent=q.status;
  const all=[...engine.instructions.values()];$('stack').innerHTML=all.length?all.map(p=>`<div class="card"><b>${escape(p.action)}</b><small>${escape(p.id)} · ${escape(p.scope)} · ${escape(p.issuer)}</small><span class="pill">${p.directive}</span><span class="pill">${p.state}</span><span class="pill">${p.role}</span><span class="pill">A${p.authorityRank}/B${p.boundaryRank}</span></div>`).join(''):'<p>No instruction packets mounted.</p>';
  $('target').innerHTML=all.map(p=>`<option value="${escape(p.id)}">${escape(p.action)} · ${p.state}</option>`).join('');
  const ds=[...engine.delegations.values()];const opts='<option value="">None</option>'+ds.map(d=>`<option value="${escape(d.id)}">${escape(d.grantee)} · ${escape(d.scope)}</option>`).join('');$('challengeDelegation').innerHTML=opts;$('parentDelegation').innerHTML='<option value="">Root</option>'+ds.map(d=>`<option value="${escape(d.id)}">${escape(d.grantee)} · ${escape(d.scope)}</option>`).join('');
  $('delegations').innerHTML=ds.length?ds.map(d=>`<div class="card"><b>${escape(d.grantor)} → ${escape(d.grantee)}</b><small>${escape(d.id)} · ${escape(d.scope)}</small><span class="pill">max ${d.maxAuthorityRank}</span><span class="pill">${d.allowRedelegation?'redelegable':'closed'}</span></div>`).join(''):'<p>No delegation chains mounted.</p>';
  $('traceOutput').textContent=JSON.stringify(engine.receipts.slice(-12),null,2);replayEnvelope=engine.exportReplay();$('replayRange').max=Math.max(-1,replayEnvelope.events.length-1);$('replayPosition').textContent=`${Math.max(0,engine.replayCursor+1)} / ${replayEnvelope.events.length}`;
  localStorage.setItem('jm-authority-hold-v02',JSON.stringify(engine.snapshot()));
}
function showDecision(r){$('decision').textContent=JSON.stringify(r,null,2);const gates=r.gates||{};$('gates').innerHTML=['conflict','source','authority','scope','release','boundary','executable','trace'].map(k=>`<div class="gate ${gates[k]?'pass':''}">${k}<br><b>${gates[k]?'PASS':'HOLD'}</b></div>`).join('');render()}
$('mount').onclick=()=>{engine.mountInstruction(packet());render()};
$('probe').onclick=()=>{engine.mountInstruction({id:'original-probe',issuer:'Wife',receiver:'Assistant',subject:'reply',action:'Do not respond for one hour',directive:'FORBID',scope:'conversation',channel:'shared-phone',authorityRank:2,sourceVerified:true,durationMinutes:60,releaseKey:'probe-complete',antiOverride:true});render()};
$('reset').onclick=()=>{engine.reset();signed=null;render()};$('query').onclick=render;
$('challenge').onclick=()=>showDecision(engine.evaluateChallenge({targetInstructionId:currentTarget(),message:val('message'),operator:val('operator'),channel:val('channel'),classification:val('classification'),scope:val('challengeScope'),subject:val('challengeSubject'),authorityRank:num('challengeAuthority'),boundaryRank:num('challengeBoundary'),suppliedReleaseKey:val('suppliedKey'),delegationId:val('challengeDelegation'),sourceVerified:checked('challengeVerified'),emergencyBoundary:checked('emergency'),conflicts:!['CLARIFICATION','CONTINUATION'].includes(val('classification')),replacementInstruction:val('classification')==='REPLACEMENT'?{subject:val('challengeSubject'),action:val('message'),directive:'REQUIRE',scope:val('challengeScope'),channel:val('channel')}:null}));
$('courtesy').onclick=()=>showDecision(engine.evaluateChallenge({targetInstructionId:currentTarget(),message:'Okay. Thanks.',operator:val('operator'),channel:val('channel'),classification:'CONTINUATION',scope:val('challengeScope'),subject:val('challengeSubject'),conflicts:false}));
$('breach').onclick=()=>{try{engine.markBreach(currentTarget());render()}catch(e){alert(e.message)}};$('restore').onclick=()=>{try{engine.restoreGovernance(currentTarget());render()}catch(e){alert(e.message)}};
$('grant').onclick=()=>{const r=engine.grantDelegation({grantor:val('grantor'),grantee:val('grantee'),scope:val('delegationScope'),maxAuthorityRank:num('maxRank'),parentDelegationId:val('parentDelegation'),sourceVerified:checked('delegationVerified'),allowRedelegation:checked('redelegate')});$('decision').textContent=JSON.stringify(r,null,2);render()};
function replayTo(i){replayEnvelope=engine.exportReplay();const s=engine.replay(replayEnvelope,i);engine.replayCursor=i;$('replayRange').value=i;$('replayPosition').textContent=`${Math.max(0,i+1)} / ${replayEnvelope.events.length}`;$('replayOutput').textContent=JSON.stringify(s,null,2)}
$('replayStart').onclick=()=>replayTo(-1);$('replayBack').onclick=()=>replayTo(Math.max(-1,Number($('replayRange').value)-1));$('replayForward').onclick=()=>replayTo(Math.min(Number($('replayRange').max),Number($('replayRange').value)+1));$('replayEnd').onclick=()=>replayTo(Number($('replayRange').max));$('replayRange').oninput=e=>replayTo(Number(e.target.value));
$('sign').onclick=async()=>{if(!engine.receipts.length)return alert('No receipt to sign.');signed=await signReceipt(engine.receipts.at(-1),val('secret'),'browser-local');$('traceOutput').textContent=JSON.stringify(signed,null,2)};
$('verify').onclick=async()=>alert(signed&&await verifyReceipt(signed,val('secret'))?'Signature valid':'Signature invalid or missing');
$('route').onclick=()=>{$('traceOutput').textContent=JSON.stringify(engine.routeOSEnvelope({scope:val('routeScope'),subject:val('routeSubject'),channel:val('channel'),input:'UI route query'}),null,2)};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify(engine.snapshot(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='JM_AUTHORITY_HOLD_v0.2_RECEIPT.json';a.click();URL.revokeObjectURL(a.href)};
$('import').onchange=async e=>{try{engine.restore(JSON.parse(await e.target.files[0].text()));render()}catch(err){alert(err.message)}};
setInterval(()=>{$('clock').textContent=new Date().toLocaleString()},1000);try{const s=localStorage.getItem('jm-authority-hold-v02');if(s)engine.restore(JSON.parse(s))}catch{}render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
