#!/usr/bin/env python3
import argparse,hashlib,json
from pathlib import Path
EXPECTED={"fault_vector": 6, "office": "DispatchRoute", "retained_symbols": ["jm_generated_dispatchroute", "routeos_interrupt_dispatch", "jm_generated_dispatchroute_announce"], "syscall_vector": 128, "timer_vector": 32, "version": "v1.6A"}
OUTPUTS={'dispatchroute.inc': '/* GENERATED DISPATCHROUTE v1.6A SOURCE 50a58585fab1ee1bbcd34e76ce99e4878c82a56118531144a5131f6f2c070a80. */\n#define JM_DISPATCHROUTE_VERSION "v1.6A"\n#define JM_DISPATCHROUTE_SOURCE_SHA256 "50a58585fab1ee1bbcd34e76ce99e4878c82a56118531144a5131f6f2c070a80"\n#define JM_DISPATCHROUTE_TIMER_VECTOR 32U\n#define JM_DISPATCHROUTE_PIC_EOI_PORT 0x20U\n#define JM_DISPATCHROUTE_PIC_EOI_VALUE 0x20U\n\nstatic struct cpu_frame *jm_generated_dispatchroute(struct cpu_frame *frame) __attribute__((noinline, used));\nstatic void jm_generated_dispatchroute_announce(void) __attribute__((noinline, used));\nstruct cpu_frame *routeos_interrupt_dispatch(struct cpu_frame *frame) __attribute__((noinline, used));\n\nconst char jm_generated_dispatchroute_source[] =\n  "[JM] DISPATCHROUTE GENERATED v1.6A SOURCE 50a58585fab1ee1bbcd34e76ce99e4878c82a56118531144a5131f6f2c070a80 ACTIVE";\n\nstatic void jm_generated_dispatchroute_announce(void) {\n  static bool announced;\n  if (!announced) { serial_write(jm_generated_dispatchroute_source); serial_write("\\n"); announced = true; }\n}\n\nstatic struct cpu_frame *jm_generated_dispatchroute(struct cpu_frame *frame) {\n  jm_generated_dispatchroute_announce();\n  if (frame->vector == JM_DISPATCHROUTE_TIMER_VECTOR) {\n    ++ticks;\n    outb(JM_DISPATCHROUTE_PIC_EOI_PORT, JM_DISPATCHROUTE_PIC_EOI_VALUE);\n    save_current(frame);\n    if ((ticks % JM_BODY_ROUTESCHEDULER_CADENCE_TICKS) == 0) {\n      serial_write("[JM] TIMER TICK "); serial_u64(ticks); serial_write(" -> ROUTESCHEDULER\\n");\n    }\n    return select_next();\n  }\n  if (frame->vector == JM_GATE_PERMISSIONGATE_VECTOR) return jm_generated_permissiongate(frame);\n  if (frame->vector == JM_FAULT_FAULTHOLD_VECTOR) return jm_generated_faulthold(frame);\n  return jm_generated_unhandled_fault(frame);\n}\n\nstruct cpu_frame *routeos_interrupt_dispatch(struct cpu_frame *frame) {\n  return jm_generated_dispatchroute(frame);\n}\n/* END GENERATED DISPATCHROUTE. */\n', 'dispatchroute.json': '{\n  "generated": {\n    "dispatchroute.inc": "83c74d882ccceaa812c0818e21519c7947acfdb2932f0b659e77bc79f2545693"\n  },\n  "retained_symbols": [\n    "jm_generated_dispatchroute",\n    "routeos_interrupt_dispatch",\n    "jm_generated_dispatchroute_announce"\n  ],\n  "source_sha256": "50a58585fab1ee1bbcd34e76ce99e4878c82a56118531144a5131f6f2c070a80",\n  "version": "v1.6A"\n}\n'}
def main():
 p=argparse.ArgumentParser();p.add_argument('source',type=Path);p.add_argument('--out-dir',type=Path,required=True);p.add_argument('--check',action='store_true');a=p.parse_args();raw=a.source.read_text()
 if json.loads(raw)!=EXPECTED or hashlib.sha256(raw.encode()).hexdigest()!='50a58585fab1ee1bbcd34e76ce99e4878c82a56118531144a5131f6f2c070a80': raise SystemExit('HOLD: source drift')
 a.out_dir.mkdir(parents=True,exist_ok=True)
 for n,d in OUTPUTS.items():
  q=a.out_dir/n
  if a.check:
   if not q.exists() or q.read_text()!=d: raise SystemExit(f'HOLD: generated {n} drift')
  else:q.write_text(d)
if __name__=='__main__':main()
