plugins { id 'com.android.application' }

android {
    namespace 'com.jmestate.librarian'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jmestate.librarian.v041a'
        minSdk 24
        targetSdk 35
        versionCode 6
        versionName '0.4.1A'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
