plugins {
    id 'com.android.application'
}

android {
    namespace 'com.jmestate.estatecompass'
    compileSdk 35

    defaultConfig {
        applicationId 'com.jmestate.estatecompass'
        minSdk 26
        targetSdk 35
        versionCode 1201
        versionName '1.2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
