(() => {
'use strict';
const VERSION='JM Verballage v0.1 First Village';
const KEY='jm_verballage_v0_1_library';
const TRACE_KEY='jm_verballage_v0_1_trace';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const now=()=>new Date().toISOString(); const uid=()=>`JMST-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`.toUpperCase();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const defaultSeeds=[
{title:'The Door That Remembered',genre:'Fairy tale',tone:'Wonder with unease',character:'Mara, a locksmith who cannot forget a sound',setting:'A village where every door opens only once',theme:'Return without reversal',momentType:'Discovery',ordinary:'Mara repairs the village doors and knows every hinge by sound.',moment:'One silent door opens by itself and reveals her childhood home exactly as it was.',response:'She enters, despite knowing the house was demolished years ago.',route:'Each room restores something she lost, but removes one certainty about the life outside.',restored:'Mara returns to the village before sunrise, and the door closes like any other.',after:'The village looks unchanged, but Mara can now hear which doors remember the people who passed through them.'},
{title:'Signal Lost, Story Found',genre:'Contemporary fable',tone:'Witty and reflective',character:'A creator whose work lives across many rooms',setting:'A living archive reached through a temperamental machine',theme:'Failure births route',momentType:'Accident',ordinary:'The creator is consolidating a large body of work in one active room.',moment:'The room suddenly stops responding at the exact point a contradiction is named.',response:'Rather than wait, the creator opens another room and carries the work forward.',route:'The interruption becomes evidence, then language, then a definition of what makes a moment.',restored:'The original room comes back online and remains useful.',after:'Nothing has been lost, but the new room, the new law and the new product now exist beside it.'}
];
const state={view:'home',library:[],trace:[],selectedId:null,parentId:null};
const Offices={
 IGNITIONBODY:{run(){state.library=load(KEY,[]);state.trace=load(TRACE_KEY,[]);if(!state.library.length){state.library=seedVillage();save();}TRACEBODY.log('IGNITIONBODY','App opened',VERSION);ROUTEBODY.to('home');}},
 ROUTEBODY:{to(view){state.view=view;$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${view}`));$$('.navbtn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='library')LIBRARYBODY.render();if(view==='map')VILLAGEBODY.render();if(view==='trace')TRACEBODY.render();window.scrollTo({top:0,behavior:'smooth'});}},
 INPUTBODY:{read(){return {title:$('#title').value.trim(),genre:$('#genre').value.trim(),tone:$('#tone').value.trim(),character:$('#character').value.trim(),setting:$('#setting').value.trim(),theme:$('#theme').value.trim(),momentType:$('#momentType').value,stages:{ordinary:$('#ordinary').value.trim(),moment:$('#moment').value.trim(),response:$('#response').value.trim(),route:$('#route').value.trim(),restored:$('#restored').value.trim(),after:$('#after').value.trim()}};},write(s){$('#title').value=s.title||'';$('#genre').value=s.genre||'';$('#tone').value=s.tone||'';$('#character').value=s.character||'';$('#setting').value=s.setting||'';$('#theme').value=s.theme||'';$('#momentType').value=s.momentType||'Choice';Object.entries(s.stages||s).forEach(([k,v])=>{const el=$(`#${k}`);if(el)el.value=v||'';});MOMENTBODY.preview();}},
 MOMENTBODY:{validate(s){const missing=[];if(!s.title)missing.push('title');for(const [k,v] of Object.entries(s.stages))if(!v)missing.push(k);return {ok:missing.length===0,missing};},preview(){const s=INPUTBODY.read();$('#previewTitle').textContent=s.title||'Untitled story-house';$('#previewStory').textContent=STORYBODY.compose(s)||'Your complete 1–6 story will appear here as you build.';const v=MOMENTBODY.validate(s);$('#gateText').innerHTML=v.ok?'<strong>BUILD GATE OPEN.</strong> All six story stages are present.':`Build gate waiting for: ${v.missing.join(', ')}.`;}},
 STORYBODY:{compose(s){if(!s||!s.stages)return'';const a=s.stages;const parts=[a.ordinary,a.moment,a.response,a.route,a.restored,a.after].filter(Boolean);return parts.join('\n\n');},save(){const raw=INPUTBODY.read();const gate=MOMENTBODY.validate(raw);if(!gate.ok){toast(`Complete: ${gate.missing.join(', ')}`);return;}const story={...raw,id:state.selectedId||uid(),createdAt:state.selectedId?(state.library.find(x=>x.id===state.selectedId)?.createdAt||now()):now(),updatedAt:now(),parentId:state.parentId||null,birthReason:state.parentId?$('#birthReason').value.trim():'',version:'DEFAULT Story Builder v1.0'};const i=state.library.findIndex(x=>x.id===story.id);if(i>=0)state.library[i]=story;else state.library.unshift(story);state.selectedId=story.id;save();TRACEBODY.log('STORYBODY',i>=0?'Story updated':'Story created',story.title);toast('Story-house saved');DETAILBODY.open(story.id);},new(parentId=null,reason=''){state.selectedId=null;state.parentId=parentId;$('#builderForm').reset();$('#birthReason').value=reason;$('#builderMode').textContent=parentId?'Child story route':'New story route';MOMENTBODY.preview();ROUTEBODY.to('builder');},generate(){const seed=structuredClone(defaultSeeds[Math.floor(Math.random()*defaultSeeds.length)]);seed.title=`${seed.title} ${Math.floor(Math.random()*90+10)}`;INPUTBODY.write({...seed,stages:seed});state.selectedId=null;state.parentId=null;$('#builderMode').textContent='Generated starting body';TRACEBODY.log('DEFAULTBODY','Generated six-stage draft',seed.title);ROUTEBODY.to('builder');toast('Generated a complete editable 1–6 story');},edit(id){const s=state.library.find(x=>x.id===id);if(!s)return;state.selectedId=id;state.parentId=s.parentId;INPUTBODY.write(s);$('#birthReason').value=s.birthReason||'';$('#builderMode').textContent='Editing story-house';ROUTEBODY.to('builder');},remove(id){const s=state.library.find(x=>x.id===id);if(!s||!confirm(`Delete “${s.title}”? Child stories will remain.`))return;state.library=state.library.filter(x=>x.id!==id);save();TRACEBODY.log('STORYBODY','Story deleted',s.title);LIBRARYBODY.render();toast('Story removed');}},
 BIRTHBODY:{seeds(s){const a=s.stages;return [
`Someone else experiences the consequence of: ${a.after}`,
`The restored state hides a second change: ${a.restored}`,
`An object, place or person from the route gains its own before and after.`,
`The story becomes known, retold or misunderstood by another character.`];},spawn(parentId,reason){const p=state.library.find(x=>x.id===parentId);if(!p)return;STORYBODY.new(parentId,reason);$('#ordinary').value=`After the events of “${p.title}”, ${reason}`;$('#moment').value='A new moment gives this consequence its own meaningful before and after.';MOMENTBODY.preview();TRACEBODY.log('BIRTHBODY','Child route opened',p.title);}},
 LIBRARYBODY:{render(){const el=$('#libraryList');if(!state.library.length){el.innerHTML='<div class="empty">No story-houses yet.</div>';return;}el.innerHTML=state.library.map(s=>`<article class="story-row"><div><h4>${esc(s.title)}</h4><div class="meta">${esc(s.genre||'Unclassified')} · ${new Date(s.updatedAt||s.createdAt).toLocaleString()}${s.parentId?' · child story':''}</div><div class="tags"><span class="tag">${esc(s.momentType||'Moment')}</span><span class="tag">${esc(s.theme||'No theme yet')}</span></div></div><div class="row-actions"><button class="btn small" data-open="${s.id}">Open</button><button class="btn small" data-edit="${s.id}">Edit</button><button class="btn small danger" data-delete="${s.id}">Delete</button></div></article>`).join('');}},
 DETAILBODY:{open(id){const s=state.library.find(x=>x.id===id);if(!s)return;const births=BIRTHBODY.seeds(s);$('#detail').innerHTML=`<article class="story-sheet"><div class="eyebrow">Story-house ${esc(s.id)}</div><h2>${esc(s.title)}</h2><div class="meta">${esc(s.genre||'')} · ${esc(s.tone||'')} · ${esc(s.momentType||'')}</div><div class="story-body">${esc(STORYBODY.compose(s))}</div><div class="half-grid"><section class="panel"><h4>The story of the story</h4><p><strong>Born from:</strong> ${s.parentId?esc(state.library.find(x=>x.id===s.parentId)?.title||s.parentId):'An original route'}</p><p><strong>Birth reason:</strong> ${esc(s.birthReason||'The user began a new story-house.')}</p><p><strong>What changed:</strong> ${esc(s.stages.after)}</p></section><section class="panel"><h4>What it could birth next</h4>${births.map((b,i)=>`<div class="birth-card"><h5>Birth route ${i+1}</h5><p>${esc(b)}</p><button class="btn small" data-spawn="${s.id}" data-reason="${esc(b)}">Build this story</button></div>`).join('')}</section></div><div class="row" style="margin-top:16px"><button class="btn" data-edit="${s.id}">Edit</button><button class="btn" data-export-json="${s.id}">Export JSON</button><button class="btn" data-export-txt="${s.id}">Export text</button><button class="btn primary" data-spawn="${s.id}" data-reason="Continue from the final changed state.">Birth another story</button></div></article>`;$('#detailModal').classList.add('open');TRACEBODY.log('LIBRARYBODY','Story opened',s.title);}},
 VILLAGEBODY:{render(){const wrap=$('#mapCanvas');const stories=state.library.slice().reverse();const positions={};const children={};stories.forEach(s=>{(children[s.parentId||'root']??=[]).push(s)});let x=60,y=60;const roots=children.root||[];const place=(s,depth,index)=>{positions[s.id]={x:60+depth*240,y:60+index*150};const kids=children[s.id]||[];kids.forEach((k,i)=>place(k,depth+1,index+i+(depth?0:roots.indexOf(s))));};roots.forEach((r,i)=>place(r,0,i));let svg='<svg class="map-lines" viewBox="0 0 1100 700" preserveAspectRatio="none"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#9b7b39"/></marker></defs>';stories.forEach(s=>{if(s.parentId&&positions[s.parentId]&&positions[s.id]){const a=positions[s.parentId],b=positions[s.id];svg+=`<path d="M ${a.x+180} ${a.y+56} C ${a.x+210} ${a.y+56}, ${b.x-30} ${b.y+56}, ${b.x} ${b.y+56}" stroke="#9b7b39" stroke-width="2" fill="none" marker-end="url(#arrow)"/>`;}});svg+='</svg>';wrap.innerHTML=svg+stories.map(s=>{const p=positions[s.id]||{x:x+=210,y:y};return`<article class="node ${s.parentId?'':'root'}" style="left:${p.x}px;top:${p.y}px"><span class="node-id">${esc(s.id)}</span><h4>${esc(s.title)}</h4><small>${esc(s.stages.after.slice(0,100))}${s.stages.after.length>100?'…':''}</small><button class="btn small" data-open="${s.id}">Open</button></article>`}).join('');}},
 TRACEBODY:{log(body,action,detail=''){state.trace.unshift({time:now(),body,action,detail});state.trace=state.trace.slice(0,250);try{localStorage.setItem(TRACE_KEY,JSON.stringify(state.trace));}catch{}},render(){$('#traceList').innerHTML=state.trace.length?state.trace.map(t=>`<div class="trace-item"><time>${new Date(t.time).toLocaleString()}</time> · <strong>${esc(t.body)}</strong> · ${esc(t.action)} ${t.detail?`— ${esc(t.detail)}`:''}</div>`).join(''):'<div class="empty">No trace receipts yet.</div>';},export(){download('JM_VERBALLAGE_TRACE.json',JSON.stringify({version:VERSION,exportedAt:now(),trace:state.trace},null,2),'application/json');}},
 RECEIPTBODY:{exportLibrary(){download('JM_VERBALLAGE_LIBRARY.json',JSON.stringify({version:VERSION,exportedAt:now(),stories:state.library},null,2),'application/json');TRACEBODY.log('RECEIPTBODY','Library exported',`${state.library.length} stories`);},importLibrary(file){const r=new FileReader();r.onload=()=>{try{const data=JSON.parse(r.result);const stories=Array.isArray(data)?data:data.stories;if(!Array.isArray(stories))throw Error('No stories array');state.library=stories;save();LIBRARYBODY.render();VILLAGEBODY.render();TRACEBODY.log('RECEIPTBODY','Library imported',`${stories.length} stories`);toast('Library imported');}catch(e){toast(`Import failed: ${e.message}`)}};r.readAsText(file);},story(id,type){const s=state.library.find(x=>x.id===id);if(!s)return;if(type==='json')download(`${slug(s.title)}.json`,JSON.stringify(s,null,2),'application/json');else download(`${slug(s.title)}.txt`,`${s.title}\n\n${STORYBODY.compose(s)}\n\n--- STORY AND A HALF ---\nBorn from: ${s.parentId||'Original route'}\nBirth reason: ${s.birthReason||'User-created'}\n`,'text/plain');TRACEBODY.log('RECEIPTBODY',`Story exported ${type}`,s.title);}}
};
const {IGNITIONBODY,ROUTEBODY,INPUTBODY,MOMENTBODY,STORYBODY,BIRTHBODY,LIBRARYBODY,DETAILBODY,VILLAGEBODY,TRACEBODY,RECEIPTBODY}=Offices;
function seedVillage(){const ids=['BROKEN-CHAT','THE-MOVE','WHAT-MAKES-A-MOMENT','DEFAULT-STORY-BUILDER','JM-VERBALLAGE'];const titles=['The Broken Chat','The Move','What Makes a Moment','The DEFAULT Story Builder','JM Verballage'];const after=[
'The chat returns, but it no longer occupies the same position in the creator’s world.',
'Two active routes now exist where previously there was one.',
'Three keeper laws remain after the waffle is removed.',
'A reusable story engine exists where there had only been a conversation.',
'Connected story-houses can now become a product rather than one stretched-out tale.'
];return titles.map((title,i)=>({id:ids[i],title,genre:'Live-origin story',tone:'Reflective with humour',character:'JM and the responding system',setting:'A working estate of connected chats',theme:'Continuity without sameness',momentType:i===0?'Accident':'Discovery',parentId:i?ids[i-1]:null,birthReason:i?after[i-1]:'A live message-stream failure',createdAt:now(),updatedAt:now(),version:'DEFAULT Story Builder v1.0',stages:{ordinary:i===0?'A productive chat is actively consolidating the estate.':`The consequences of “${titles[i-1]}” already exist.`,moment:i===0?'The message stream fails immediately after the contradiction is named.':`A new insight separates itself from the previous story and gains its own before and after.`,response:'JM carries the useful material forward instead of waiting for the route to repair itself.',route:'The interruption is examined, clarified, trimmed and converted into a usable body.',restored:'The earlier material remains available and continues to be used.',after:after[i]}}));}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state.library));}catch{}}
function load(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),300)}
function slug(s){return s.toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_|_$/g,'')}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.view)ROUTEBODY.to(b.dataset.view);if(b.id==='newStory')STORYBODY.new();if(b.id==='generateStory')STORYBODY.generate();if(b.id==='saveStory')STORYBODY.save();if(b.id==='clearStory')STORYBODY.new(state.parentId,$('#birthReason').value);if(b.id==='closeModal')$('#detailModal').classList.remove('open');if(b.dataset.open)DETAILBODY.open(b.dataset.open);if(b.dataset.edit){$('#detailModal').classList.remove('open');STORYBODY.edit(b.dataset.edit)}if(b.dataset.delete)STORYBODY.remove(b.dataset.delete);if(b.dataset.spawn){$('#detailModal').classList.remove('open');BIRTHBODY.spawn(b.dataset.spawn,b.dataset.reason||'A consequence gains its own story route.')}if(b.dataset.exportJson)RECEIPTBODY.story(b.dataset.exportJson,'json');if(b.dataset.exportTxt)RECEIPTBODY.story(b.dataset.exportTxt,'txt');if(b.id==='exportLibrary')RECEIPTBODY.exportLibrary();if(b.id==='exportTrace')TRACEBODY.export();if(b.id==='importLibraryBtn')$('#importLibrary').click();});$('#builderForm').addEventListener('input',MOMENTBODY.preview);$('#importLibrary').addEventListener('change',e=>e.target.files[0]&&RECEIPTBODY.importLibrary(e.target.files[0]));$('#detailModal').addEventListener('click',e=>{if(e.target.id==='detailModal')e.currentTarget.classList.remove('open')});}
document.addEventListener('DOMContentLoaded',()=>{bind();Offices.IGNITIONBODY.run();if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});});
window.JM={VERSION,Offices,state};
})();
