#!/usr/bin/env python3
import pathlib, sys
text = pathlib.Path(sys.argv[1]).read_text(errors='replace')
ordered = [
 'JM BOOT IMAGE LOADED','ROUTEOS KERNEL ENTRY','PRIVILEGED EXECUTION ACTIVE',
 'ONEBODY GENERATED ROUTEOS KERNEL LOADED: BLUEPRINT_SHA256',
 'MEMORY INITIALISED: ALLOCATE/RELEASE PASS','INTERRUPT ROUTE ACTIVE',
 'BODYREGISTRY: TWO GENERATED USER BODIES REGISTERED',
 'ONEBODY GENERATED USER BODY 1 LOADED: SOURCE_SHA256','ONEBODY GENERATED USER BODY 2 LOADED: SOURCE_SHA256',
 'PERMISSIONGATE: INT 0x80 CONTROLLED ENTRY ACTIVE','DEVICE OUTPUT: JM-CONTROLLED SERIAL ACTIVE','ROUTESCHEDULER: ENTERING USER BODY 1',
 'GENERATED USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
 'GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN',
 'GENERATED USER BODY 2 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
 'GENERATED USER BODY 2 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 2 -> KERNEL RETURN',
 'FAULTHOLD: GENERATED USER BODY 2 INVALID OPCODE CAUGHT','RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES',
 'GENERATED USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
 'GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN'
]
pos=-1
for item in ordered:
    pos2=text.find(item,pos+1)
    if pos2<0: raise SystemExit(f'HOLD: missing or out-of-order trace: {item}')
    pos=pos2
if 'TIMER TICK ' not in text or '-> ROUTESCHEDULER' not in text: raise SystemExit('HOLD: no PIT scheduler receipt')
if text.count('ONEBODY GENERATED ROUTEOS KERNEL LOADED: BLUEPRINT_SHA256') != 1: raise SystemExit('HOLD: generated kernel identity count mismatch')
if text.count('FAULTHOLD: GENERATED USER BODY 2 INVALID OPCODE CAUGHT') != 1: raise SystemExit('HOLD: Body 2 fault count mismatch')
if text.count('RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES') != 1: raise SystemExit('HOLD: recovery count mismatch')
if 'FAULTHOLD: GENERATED USER BODY 1' in text: raise SystemExit('HOLD: safe Body 1 faulted')
print('GENERATED_ROUTEOS_KERNEL_TRACE PASS')
print('TWO_GENERATED_BODIES_TRACE PASS')
print('GENERATED_KERNEL_PERMISSIONGATE PASS')
print('GENERATED_KERNEL_FAULTHOLD_RECOVERY PASS')
print('POST_FAULT_GENERATED_BODY_1_CONTINUATION PASS')
print('TIMER_DRIVEN_GENERATED_KERNEL_SCHEDULER PASS')
