import {Trace,applyAction,assignments,blocks,digest,need,parseAction,setPath,valueOf} from './native-core.mjs';

export const FlowTalkBodyRoute={
 parse(source){const routes=blocks(source,'bodyroute').map(b=>{const d=assignments(b.body);const action=b.body.match(/\baction\s+(.+)/);need(d.state&&d.utterance&&d.meaning&&d.route&&action,'FTBR_CORE',`BodyRoute ${b.name} incomplete.`);return{type:'FTBRRoute',name:b.name,state:d.state,utterance:d.utterance,meaning:d.meaning,route:d.route,action:parseAction(action[1])};});need(routes.length,'FTBR_NONE','FlowTalk Body Route requires bodyroute.');return{type:'FTBRProgram',routes};},
 lower(ast){return{type:'FTBRBodySpeechGraph',nodes:ast.routes.flatMap(r=>[{id:`state:${r.name}`,value:r.state},{id:`speech:${r.name}`,value:r.utterance},{id:`meaning:${r.name}`,value:r.meaning},{id:`route:${r.name}`,value:r.route}]),edges:ast.routes.flatMap(r=>[{from:`state:${r.name}`,to:`speech:${r.name}`,kind:'embodies'},{from:`speech:${r.name}`,to:`meaning:${r.name}`,kind:'means'},{from:`meaning:${r.name}`,to:`route:${r.name}`,kind:'routes'}])};},
 execute(source,input,state={}){const ast=this.parse(source),ir=this.lower(ast),route=ast.routes.find(r=>r.state===input.state&&r.utterance===input.utterance);need(route,'FTBR_NO_MATCH','No body-state utterance route.');const out=structuredClone(state),trace=new Trace('FlowTalk Body Route');applyAction(route.action,out,trace);out.bodyState=route.state;out.spokenMeaning=route.meaning;out.nextRoute=route.route;trace.emit('body.speech.routed',route);return{ast,ir,state:out,trace:trace.events,receipt:trace.receipt('merge body state with spoken meaning into route action',out)};}
};

export const CommandGlyphs={
 parse(source){const commands=[];for(const line of String(source).split(/\r?\n/).map(v=>v.trim()).filter(Boolean)){const m=line.match(/^command\s+(\S+)\s+pressure=([A-Za-z_][\w.-]*)\s+route=([A-Za-z_][\w.-]*)\s+action\s+(.+)$/);need(m,'CMDGLYPH_BAD_DECL',line);commands.push({symbol:m[1],pressure:m[2],route:m[3],action:parseAction(m[4])});}need(commands.length,'CMDGLYPH_NONE','Command Glyphs requires commands.');need(new Set(commands.map(c=>c.symbol)).size===commands.length,'CMDGLYPH_DUPLICATE','Duplicate command glyph.');return{type:'CommandGlyphProgram',commands};},
 lower(ast){return{type:'CommandGlyphPressureGraph',nodes:ast.commands.map(c=>({id:`glyph:${c.symbol}`,...c})),edges:ast.commands.map(c=>({from:`glyph:${c.symbol}`,to:`route:${c.route}`,kind:c.pressure}))};},
 execute(source,symbol,state={}){const ast=this.parse(source),ir=this.lower(ast),cmd=ast.commands.find(c=>c.symbol===symbol);need(cmd,'CMDGLYPH_UNKNOWN',symbol);const out=structuredClone(state),trace=new Trace('Command Glyphs');applyAction(cmd.action,out,trace);out.pressure=cmd.pressure;out.nextRoute=cmd.route;trace.emit('glyph.commanded',cmd);return{ast,ir,state:out,trace:trace.events,receipt:trace.receipt('turn glyph pressure into route action',out)};}
};

export const MirrorPairFingerLaw={
 parse(source){const pairs=blocks(source,'pair').map(b=>{const d=assignments(b.body);need(d.left_name&&d.right_move&&d.route,'MIRROR_CORE',`Pair ${b.name} incomplete.`);return{name:b.name,leftName:d.left_name,rightMove:d.right_move,route:d.route};});need(pairs.length,'MIRROR_NONE','Mirror-Pair requires pair.');return{type:'MirrorPairProgram',pairs};},
 lower(ast){return{type:'MirrorPairGraph',nodes:ast.pairs.flatMap(p=>[{id:`left:${p.name}`,identity:p.leftName},{id:`right:${p.name}`,movement:p.rightMove},{id:`route:${p.name}`,route:p.route}]),edges:ast.pairs.flatMap(p=>[{from:`left:${p.name}`,to:`route:${p.name}`,kind:'names'},{from:`right:${p.name}`,to:`route:${p.name}`,kind:'moves'}])};},
 execute(source,input){const ast=this.parse(source),ir=this.lower(ast),p=ast.pairs[0];need(input.left===p.leftName&&input.right===p.rightMove,'MIRROR_PAIR_MISMATCH','Naming and movement hands do not match.');const state={leftIdentity:p.leftName,rightMovement:p.rightMove,wholeRoute:p.route,identitiesPreserved:true};const trace=new Trace('Mirror-Pair Finger Law');trace.emit('hands.paired',state);return{ast,ir,state,trace:trace.events,receipt:trace.receipt('pair naming and movement without competition',state)};}
};

export const PrayerHands={
 parse(source){const prayers=blocks(source,'prayer').map(b=>{const d=assignments(b.body);need(d.hand_a&&d.hand_b&&d.contact&&d.max_delta!=null&&d.route,'PRAYER_CORE',`Prayer ${b.name} incomplete.`);return{name:b.name,handA:d.hand_a,handB:d.hand_b,contact:d.contact,maxDelta:Number(d.max_delta),route:d.route};});need(prayers.length,'PRAYER_NONE','Prayer Hands requires prayer.');return{type:'PrayerHandsProgram',prayers};},
 lower(ast){return{type:'PairedContactGraph',nodes:ast.prayers.flatMap(p=>[{id:`a:${p.name}`,hand:p.handA},{id:`b:${p.name}`,hand:p.handB},{id:`contact:${p.name}`,contact:p.contact},{id:`route:${p.name}`,route:p.route}]),edges:ast.prayers.flatMap(p=>[{from:`a:${p.name}`,to:`contact:${p.name}`,kind:'join'},{from:`b:${p.name}`,to:`contact:${p.name}`,kind:'join'},{from:`contact:${p.name}`,to:`route:${p.name}`,kind:'unified'}])};},
 execute(source,input){const ast=this.parse(source),ir=this.lower(ast),p=ast.prayers[0];need(input.handA===p.handA&&input.handB===p.handB,'PRAYER_HAND_MISMATCH','Hands mismatch.');const delta=Math.abs(Number(input.forceA)-Number(input.forceB));need(delta<=p.maxDelta,'PRAYER_UNBALANCED',delta);const state={handA:p.handA,handB:p.handB,contact:p.contact,delta,stable:true,nextRoute:p.route};const trace=new Trace('Prayer Hands / Paired Contact Logic');trace.emit('contact.joined',state);return{ast,ir,state,trace:trace.events,receipt:trace.receipt('join paired force into stable unified route',state)};}
};

export const ColdDingJoin={
 parse(source){const joins=blocks(source,'join').map(b=>{const d=assignments(b.body);need(d.trace&&d.ding&&d.memory,'COLDJOIN_CORE',`Join ${b.name} incomplete.`);return{name:b.name,traceId:d.trace,dingId:d.ding,memory:d.memory};});need(joins.length,'COLDJOIN_NONE','Cold Ding Join requires join.');return{type:'ColdDingJoinProgram',joins};},
 lower(ast){return{type:'ColdDingMemoryGraph',nodes:ast.joins.flatMap(j=>[{id:`trace:${j.traceId}`},{id:`ding:${j.dingId}`},{id:`memory:${j.memory}`}]),edges:ast.joins.flatMap(j=>[{from:`trace:${j.traceId}`,to:`memory:${j.memory}`,kind:'remember'},{from:`ding:${j.dingId}`,to:`memory:${j.memory}`,kind:'prove'}])};},
 execute(source,inputs){const ast=this.parse(source),ir=this.lower(ast),j=ast.joins[0];need(inputs.trace?.id===j.traceId&&inputs.ding?.id===j.dingId,'COLDJOIN_INPUT_MISMATCH','Trace/Ding mismatch.');const payload={join:j.name,trace:inputs.trace,ding:inputs.ding,memory:j.memory};const state={...payload,coldDigest:digest(payload)};const trace=new Trace('Cold Ding Join');trace.emit('proof.remembered',state);return{ast,ir,state,trace:trace.events,receipt:trace.receipt('join live trace and stored Ding into receipt memory',state)};},
 verify(state){const payload={join:state.join,trace:state.trace,ding:state.ding,memory:state.memory};need(state.coldDigest===digest(payload),'COLDJOIN_TAMPERED','Cold Ding memory digest mismatch.');return true;}
};

const RECORP_MODES={'!':'regroup-now','?':'inspect','~':'soft-regroup','.lock':'hold','→':'route-forward'};
export const RECORP={
 parse(source){const m=String(source).trim().match(/^RECORP(!|\?|~|\.lock|→)\s+([A-Za-z_][\w.-]*)$/);need(m,'RECORP_BAD_COMMAND','Use RECORP!, RECORP?, RECORP~, RECORP.lock or RECORP→.');return{type:'RECORPCommand',mode:RECORP_MODES[m[1]],mark:m[1],body:m[2]};},
 lower(ast){return{type:'RECORPRegroupNode',id:`recorp:${ast.body}`,mode:ast.mode,mark:ast.mark};},
 execute(source,state={}){const ast=this.parse(source),ir=this.lower(ast),out=structuredClone(state),trace=new Trace('RECORP');out.bodies??={};const body=out.bodies[ast.body]??={parts:[],state:'scattered'};if(ast.mode==='inspect')body.inspection={parts:body.parts.length,state:body.state};else if(ast.mode==='hold')body.state='locked';else if(ast.mode==='soft-regroup')body.state='forming';else if(ast.mode==='route-forward'){body.state='routing';out.nextRoute=`${ast.body}.forward`;}else body.state='grouped';out.bodies[ast.body]=body;trace.emit('body.recorped',{body:ast.body,mode:ast.mode,state:body.state});return{ast,ir,state:out,trace:trace.events,receipt:trace.receipt('regroup scattered material into governed body state',out)};}
};
