import {Trace,assignments,blocks,digest,listOf,need,stable,valueOf} from './native-core.mjs';

export const BuildGates={
 parse(source){const builds=blocks(source,'build').map(b=>{const d=assignments(b.body);const gates=listOf(d.gates).map(String);need(d.source&&gates.length&&d.receipt,'GATES_CORE',`Build ${b.name} incomplete.`);const required=['source','signal','route','state','trace','body','receipt','rebuild'];required.forEach(g=>need(gates.includes(g),'GATES_MISSING',g));return{name:b.name,source:d.source,gates,receipt:d.receipt};});need(builds.length,'GATES_NONE','Build Gates requires build.');return{type:'BuildGateProgram',builds};},
 lower(ast){return{type:'BuildGateChain',chains:ast.builds.map(b=>({name:b.name,nodes:b.gates.map((g,i)=>({id:`${b.name}:${g}`,gate:g,index:i})),edges:b.gates.slice(1).map((g,i)=>({from:`${b.name}:${b.gates[i]}`,to:`${b.name}:${g}`,kind:'next'}))}))};},
 execute(source,contacts={}){const ast=this.parse(source),ir=this.lower(ast),b=ast.builds[0],trace=new Trace('Build Gates'),passed=[];for(const gate of b.gates){need(contacts[gate]===true,'BUILD_GATE_FAILED',gate,{passed});passed.push(gate);trace.emit('gate.passed',{gate});}const state={build:b.name,source:b.source,passed,receipt:b.receipt,status:'PASS'};return{ast,ir,state,trace:trace.events,receipt:trace.receipt('pass source through complete JM build gate',state)};}
};

export const OneBodyDelivery={
 parse(source){const packs=blocks(source,'package').map(b=>{const d=assignments(b.body);need(d.source&&d.build&&d.receipt&&d.package&&d.open_first,'DELIVERY_CORE',`Package ${b.name} incomplete.`);return{name:b.name,source:d.source,build:d.build,receipt:d.receipt,package:d.package,openFirst:d.open_first};});need(packs.length,'DELIVERY_NONE','OneBody Delivery requires package.');return{type:'OneBodyDeliveryProgram',packs};},
 lower(ast){return{type:'OneBodyDeliveryGraph',nodes:ast.packs.flatMap(p=>['source','build','receipt','package','openFirst'].map(k=>({id:`${p.name}:${k}`,value:p[k]}))),edges:ast.packs.flatMap(p=>[{from:`${p.name}:source`,to:`${p.name}:build`,kind:'build'},{from:`${p.name}:build`,to:`${p.name}:receipt`,kind:'prove'},{from:`${p.name}:receipt`,to:`${p.name}:package`,kind:'seal'},{from:`${p.name}:package`,to:`${p.name}:openFirst`,kind:'open'}])};},
 execute(source,files={}){const ast=this.parse(source),ir=this.lower(ast),p=ast.packs[0];need(files[p.source]&&files[p.receipt]&&files[p.openFirst],'DELIVERY_FILE_MISSING','Delivery source, receipt or OPEN_FIRST missing.');const manifest={name:p.name,source:p.source,build:p.build,receipt:p.receipt,package:p.package,openFirst:p.openFirst,files:Object.keys(files).sort()};const state={...manifest,sha256:digest(manifest),recoverable:true};const trace=new Trace('OneBody Delivery');trace.emit('package.sealed',state);return{ast,ir,state,trace:trace.events,receipt:trace.receipt('turn source and receipt into recoverable OPEN_FIRST package',state)};}
};

export class CadenPad{
 constructor(){this.projects=new Map();this.trace=new Trace('CadenPad');}
 parse(source){const pads=blocks(source,'pad').map(b=>{const d=assignments(b.body);const tests=listOf(d.tests).map(String);need(d.language&&d.source&&tests.length&&d.savepack,'PAD_CORE',`Pad ${b.name} incomplete.`);return{name:b.name,language:d.language,source:d.source,tests,savepack:d.savepack};});need(pads.length,'PAD_NONE','CadenPad requires pad.');return{type:'CadenPadProgram',pads};}
 open(source){const ast=this.parse(source),pad=ast.pads[0];this.projects.set(pad.name,{...pad,history:[pad.source],testResults:[]});this.trace.emit('pad.opened',{name:pad.name,language:pad.language});return pad.name;}
 edit(name,next){const p=this.projects.get(name);need(p,'PAD_UNKNOWN',name);p.source=next;p.history.push(next);this.trace.emit('pad.edited',{name,revision:p.history.length});}
 test(name,runners={}){const p=this.projects.get(name);need(p,'PAD_UNKNOWN',name);p.testResults=p.tests.map(test=>({test,passed:typeof runners[test]==='function'&&Boolean(runners[test](p.source))}));need(p.testResults.every(r=>r.passed),'PAD_TEST_FAILED','CadenPad test failed.',p.testResults);this.trace.emit('pad.tested',{name,results:p.testResults});return p.testResults;}
 save(name){const p=this.projects.get(name);need(p,'PAD_UNKNOWN',name);const state={name,savepack:p.savepack,source:p.source,history:p.history,testResults:p.testResults,digest:digest(p)};this.trace.emit('pad.saved',state);return{state,trace:this.trace.events,receipt:this.trace.receipt('edit test and save coding body without losing history',state)};}
}

export const CadingIR={
 parse(source){const nodes=[];const links=[];for(const line of String(source).split(/\r?\n/).map(v=>v.trim()).filter(Boolean)){let m=line.match(/^node\s+([A-Za-z_][\w.-]*)\s+kind=([A-Za-z_][\w.-]*)\s+value=(.+)$/);if(m){nodes.push({id:m[1],kind:m[2],value:valueOf(m[3])});continue;}m=line.match(/^link\s+([A-Za-z_][\w.-]*)\s*->\s*([A-Za-z_][\w.-]*)\s+kind=([A-Za-z_][\w.-]*)$/);if(m){links.push({from:m[1],to:m[2],kind:m[3]});continue;}throw Object.assign(new Error(`Invalid Cading IR line ${line}`),{code:'IR_BAD_LINE'});}need(nodes.length,'IR_NO_NODES','Cading IR requires nodes.');const ids=new Set(nodes.map(n=>n.id));links.forEach(l=>need(ids.has(l.from)&&ids.has(l.to),'IR_UNKNOWN_NODE',`${l.from}->${l.to}`));return{type:'CadingIRProgram',nodes,links};},
 lower(ast){return{schema:'jm.cading.ir/1.0',nodes:ast.nodes,links:ast.links,hash:digest(ast)};},
 execute(source){const ast=this.parse(source),ir=this.lower(ast),trace=new Trace('Cading IR / OneBody IR');const state={nodeCount:ir.nodes.length,linkCount:ir.links.length,hash:ir.hash,identityPreserved:true};trace.emit('ir.verified',state);return{ast,ir,state,trace:trace.events,receipt:trace.receipt('verify identity-preserving neutral body structure',state)};}
};

export const CadingCompiler={
 parse(source){const raw=String(source).trim();need(raw.endsWith('.✓'),'COMP_FULLSTOP','Cading compiler requires Fullstopped source.');const line=raw.slice(0,-2);need((line.match(/=/g)||[]).length===1,'COMP_RELATION','Compiler source requires one landing relation.');const [left,landing]=line.split('=').map(v=>v.trim());need(left&&landing,'COMP_SIDE','Compiler relation sides required.');return{type:'CadingCompileUnit',variants:left.split(',').map(v=>v.trim()),landing};},
 lower(ast){const nodes=ast.variants.map((v,i)=>({id:`source${i}`,kind:'source',value:v})).concat([{id:'landing',kind:'landing',value:ast.landing}]);const links=ast.variants.map((_,i)=>({from:`source${i}`,to:'landing',kind:'speakuals'}));return{schema:'jm.cading.compiler-ir/1.0',nodes,links};},
 emit(ir,target='javascript'){need(['javascript','typescript','rust','cpp','wasm'].includes(target),'COMP_TARGET',target);const body=target==='javascript'?`export const landing=${JSON.stringify(ir.nodes.at(-1).value)};`:target==='rust'?`pub const LANDING: &str = ${JSON.stringify(ir.nodes.at(-1).value)};`:`TARGET ${target} LANDING ${ir.nodes.at(-1).value}`;return{target,body,digest:digest({target,body})};},
 execute(source,target='javascript'){const ast=this.parse(source),ir=this.lower(ast),output=this.emit(ir,target),trace=new Trace('Cading Compiler');trace.emit('source.parsed',{variants:ast.variants.length,landing:ast.landing});trace.emit('target.emitted',{target,digest:output.digest});return{ast,ir,output,trace:trace.events,receipt:trace.receipt('compile Cading source into target without target governing source',output)};}
};

export const HybridAutoCompiler={
 parse(source){const builds=blocks(source,'hybrid').map(b=>{const d=assignments(b.body);const targets=listOf(d.targets).map(String);const constraints=listOf(d.constraints).map(String);need(d.source&&targets.length&&d.prefer,'HYBRID_CORE',`Hybrid ${b.name} incomplete.`);return{name:b.name,source:d.source,targets,constraints,prefer:d.prefer};});need(builds.length,'HYBRID_NONE','Hybrid Auto-Compiler requires hybrid build.');return{type:'HybridCompilerProgram',builds};},
 choose(build){if(build.targets.includes(build.prefer))return build.prefer;if(build.constraints.includes('browser')&&build.targets.includes('javascript'))return'javascript';if(build.constraints.includes('native')&&build.targets.includes('rust'))return'rust';return build.targets[0];},
 execute(source,sources){const ast=this.parse(source),build=ast.builds[0],target=this.choose(build);need(sources[build.source],'HYBRID_SOURCE_MISSING',build.source);const compiled=CadingCompiler.execute(sources[build.source],target);const trace=new Trace('Hybrid Auto-Compiler');const state={build:build.name,source:build.source,target,constraints:build.constraints,output:compiled.output,sourceAuthority:'Cading',targetAuthority:false};trace.emit('target.selected',{target,constraints:build.constraints});trace.emit('hybrid.compiled',{digest:compiled.output.digest});return{ast,state,compiled,trace:trace.events,receipt:trace.receipt('select delivery target while preserving JM source authority',state)};}
};
