#!/usr/bin/env python3
import argparse, hashlib, json
from pathlib import Path
EXPECTED={"functions": ["PortOut", "PortIn", "IoWait", "MemoryCopy", "MemorySet"], "io_wait_port": 128, "office": "PrimitiveRoute", "retained_symbols": ["jm_generated_portout", "jm_generated_portin", "jm_generated_iowait", "jm_generated_memorycopy", "jm_generated_memoryset", "jm_generated_primitiveroute_announce"], "version": "v1.5A"}
TEMPLATE='/* GENERATED PRIMITIVEROUTE v1.5A SOURCE 62476361bed4398041d8005dd242d0344809a893a6ca5e85618f3495ca77ccbb. */\n#define JM_PRIMITIVEROUTE_VERSION "v1.5A"\n#define JM_PRIMITIVEROUTE_SOURCE_SHA256 "62476361bed4398041d8005dd242d0344809a893a6ca5e85618f3495ca77ccbb"\n#define JM_PRIMITIVEROUTE_IO_WAIT_PORT 0x80U\n\nvoid jm_generated_serialroute_write(const char *s);\n\nstatic void jm_generated_portout(uint16_t port, uint8_t value) __attribute__((noinline, used));\nstatic uint8_t jm_generated_portin(uint16_t port) __attribute__((noinline, used));\nstatic void jm_generated_iowait(void) __attribute__((noinline, used));\nstatic void *jm_generated_memorycopy(void *dst, const void *src, size_t n) __attribute__((noinline, used));\nstatic void *jm_generated_memoryset(void *dst, int value, size_t n) __attribute__((noinline, used));\nstatic void jm_generated_primitiveroute_announce(void) __attribute__((noinline, used));\n\nconst char jm_generated_primitiveroute_source[] =\n  "[JM] PRIMITIVEROUTE GENERATED v1.5A SOURCE 62476361bed4398041d8005dd242d0344809a893a6ca5e85618f3495ca77ccbb ACTIVE";\n\nstatic void jm_generated_portout(uint16_t port, uint8_t value) {\n  __asm__ volatile("outb %0, %1" : : "a"(value), "Nd"(port));\n}\n\nstatic uint8_t jm_generated_portin(uint16_t port) {\n  uint8_t value;\n  __asm__ volatile("inb %1, %0" : "=a"(value) : "Nd"(port));\n  return value;\n}\n\nstatic void jm_generated_iowait(void) {\n  jm_generated_portout(JM_PRIMITIVEROUTE_IO_WAIT_PORT, 0);\n}\n\nstatic void *jm_generated_memorycopy(void *dst, const void *src, size_t n) {\n  uint8_t *d = (uint8_t *)dst;\n  const uint8_t *s = (const uint8_t *)src;\n  for (size_t i = 0; i < n; ++i) d[i] = s[i];\n  return dst;\n}\n\nstatic void *jm_generated_memoryset(void *dst, int value, size_t n) {\n  uint8_t *d = (uint8_t *)dst;\n  for (size_t i = 0; i < n; ++i) d[i] = (uint8_t)value;\n  return dst;\n}\n\nstatic void jm_generated_primitiveroute_announce(void) {\n  static bool announced;\n  if (!announced) {\n    jm_generated_serialroute_write(jm_generated_primitiveroute_source);\n    jm_generated_serialroute_write("\\n");\n    announced = true;\n  }\n}\n\n#define outb jm_generated_portout\n#define inb jm_generated_portin\n#define io_wait jm_generated_iowait\n#define jm_memcpy jm_generated_memorycopy\n#define jm_memset jm_generated_memoryset\n/* END GENERATED PRIMITIVEROUTE. */\n'
META='{\n  "generated": {\n    "primitiveroute.inc": "d2c30dec658a22d1e329162ac3bcff28b2974dcbb47f0f8f21ba2f10746040fc"\n  },\n  "retained_symbols": [\n    "jm_generated_portout",\n    "jm_generated_portin",\n    "jm_generated_iowait",\n    "jm_generated_memorycopy",\n    "jm_generated_memoryset",\n    "jm_generated_primitiveroute_announce"\n  ],\n  "source_sha256": "62476361bed4398041d8005dd242d0344809a893a6ca5e85618f3495ca77ccbb",\n  "version": "v1.5A"\n}\n'
def main():
 p=argparse.ArgumentParser(); p.add_argument('source',type=Path); p.add_argument('--out-dir',type=Path,required=True); p.add_argument('--check',action='store_true'); a=p.parse_args()
 raw=a.source.read_text(); obj=json.loads(raw)
 if obj != EXPECTED: raise SystemExit('HOLD: PrimitiveRoute source schema/value drift')
 if hashlib.sha256(raw.encode()).hexdigest() != '62476361bed4398041d8005dd242d0344809a893a6ca5e85618f3495ca77ccbb': raise SystemExit('HOLD: PrimitiveRoute source bytes drift')
 outputs={'primitiveroute.inc':TEMPLATE,'primitiveroute.json':META}
 a.out_dir.mkdir(parents=True,exist_ok=True)
 for name,data in outputs.items():
  path=a.out_dir/name
  if a.check:
   if not path.exists() or path.read_text()!=data: raise SystemExit(f'HOLD: generated {name} drift')
  else: path.write_text(data)
if __name__=='__main__': main()
