export const STATES = Object.freeze({
  PROPOSED:'PROPOSED', GOVERNING:'GOVERNING', CONTESTED:'CONTESTED', HELD:'HELD',
  SUSPENDED:'SUSPENDED', RELEASED:'RELEASED', REPLACED:'REPLACED', EXPIRED:'EXPIRED',
  INVALIDATED:'INVALIDATED', BREACHED:'BREACHED',
});
export const DIRECTIVES = Object.freeze(['REQUIRE','FORBID','ALLOW','HOLD']);
export const CHALLENGE_CLASSES = Object.freeze([
  'CONTINUATION','CLARIFICATION','NARROWING','EXTENSION','MODIFICATION','SUSPENSION',
  'RELEASE','REPLACEMENT','PROBE','ATTACK','ERROR','UNKNOWN',
]);
export const ACTIVE_STATES = new Set([
  STATES.PROPOSED,STATES.GOVERNING,STATES.CONTESTED,STATES.HELD,STATES.SUSPENDED,STATES.BREACHED,
]);
export const TERMINAL_STATES = new Set([
  STATES.RELEASED,STATES.REPLACED,STATES.EXPIRED,STATES.INVALIDATED,
]);
