import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
const root=path.resolve(process.argv[2]||'.');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'body-manifest.json'),'utf8'));
const parts=manifest.payload_parts;
if(!Array.isArray(parts)||parts.length!==10) throw new Error(`unexpected segment count ${parts?.length}`);
const segmentBuffers=parts.map(p=>fs.readFileSync(path.join(root,p)));
if(JSON.stringify(segmentBuffers.map(b=>b.length))!==JSON.stringify(manifest.payload_segment_bytes)) throw new Error('segment size mismatch');
const gz=Buffer.concat(segmentBuffers);
const hash=b=>crypto.createHash('sha256').update(b).digest('hex').toUpperCase();
if(gz.length!==manifest.payload_gzip_bytes) throw new Error(`gzip bytes ${gz.length}/${manifest.payload_gzip_bytes}`);
if(hash(gz)!==manifest.payload_gzip_sha256) throw new Error(`gzip sha ${hash(gz)}`);
const html=zlib.gunzipSync(gz);
const sha=hash(html);
const text=html.toString('utf8');
const ids=[...text.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);
const refs=[...text.matchAll(/\$\('([^']+)'\)/g)].map(m=>m[1]);
const missing=[...new Set(refs.filter(x=>!ids.includes(x)))];
const rooms=[...text.matchAll(/<section id="room-([^"]+)" class="room/g)].map(m=>m[1]).sort();
const nav=[...text.matchAll(/data-room="([^"]+)"/g)].map(m=>m[1]).sort();
const loader=fs.readFileSync(path.join(root,'index.html'));
const checks={runtimeHash:sha===manifest.runtime_sha256,gzipHash:hash(gz)===manifest.payload_gzip_sha256,loaderHash:hash(loader)===manifest.loader_sha256,title:text.includes('JM FTR Participation Engine v9.0'),beyondRoom:text.includes('id="room-beyond"'),sixStages:['v4','v5','v6','v7','v8','v9'].every(x=>text.includes(`data-beyond-panel="${x}"`)),formal512:text.includes('for(let i=0;i<512;i++'),uniqueIds:new Set(ids).size===ids.length,missingRefs:missing.length===0,roomNav:JSON.stringify(rooms)===JSON.stringify(nav),physicalBoundary:manifest.claim_boundary.includes('No real sensor')};
console.log(JSON.stringify({checks,sha,gzipSha:hash(gz),gzipBytes:gz.length,segmentBytes:segmentBuffers.map(b=>b.length),missing,rooms},null,2));
if(!Object.values(checks).every(Boolean))process.exit(1);
