import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import zlib from 'node:zlib';
const root=path.resolve(process.argv[2]||'.');
const parts=["payload/payload-000.b64", "payload/pair-001-002.b64", "payload/pair-003-004.b64", "payload/pair-005-006.b64", "payload/pair-007-008.b64"];
const b64=parts.map(p=>fs.readFileSync(path.join(root,p),'utf8')).join('');
const html=zlib.gunzipSync(Buffer.from(b64,'base64'));
const manifest=JSON.parse(fs.readFileSync(path.join(root,'body-manifest.json'),'utf8'));
const sha=crypto.createHash('sha256').update(html).digest('hex').toUpperCase();
const text=html.toString('utf8');
const ids=[...text.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]);
const refs=[...text.matchAll(/\$\('([^']+)'\)/g)].map(m=>m[1]);
const missing=[...new Set(refs.filter(x=>!ids.includes(x)))];
const rooms=[...text.matchAll(/<section id="room-([^"]+)" class="room/g)].map(m=>m[1]).sort();
const nav=[...text.matchAll(/data-room="([^"]+)"/g)].map(m=>m[1]).sort();
const checks={runtimeHash:sha===manifest.runtime_sha256,title:text.includes('JM FTR Participation Engine v9.0'),beyondRoom:text.includes('id="room-beyond"'),sixStages:['v4','v5','v6','v7','v8','v9'].every(x=>text.includes(`data-beyond-panel="${x}"`)),formal512:text.includes('for(let i=0;i<512;i++'),uniqueIds:new Set(ids).size===ids.length,missingRefs:missing.length===0,roomNav:JSON.stringify(rooms)===JSON.stringify(nav)};
console.log(JSON.stringify({checks,sha,missing,rooms},null,2));
if(!Object.values(checks).every(Boolean))process.exit(1);
