plugins { id 'com.android.application' }

android {
    namespace 'com.jmisjustme.estatesteward'
    compileSdk 36
    buildToolsVersion '36.0.0'

    defaultConfig {
        applicationId 'com.jmisjustme.estatesteward'
        minSdk 29
        targetSdk 36
        versionCode 9
        versionName '0.9B'
    }

    buildTypes {
        debug {
            applicationIdSuffix '.debug'
            versionNameSuffix '-debug'
        }
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
