/* JM ESTATE CONTACT ORGAN v1.0
 * TRANSFER THE ORGAN WHERE THE MEANING SURVIVES; ADAPT THE CARRIER WHERE THE PLATFORM CHANGES.
 * OWNER USES; THE BODY PROVES. NO DING, NO CLAIM.
 */
(()=>{'use strict';
const VERSION='1.0.0',OWNER='OWNER USES; THE BODY PROVES.',CLAIM='NO DING, NO CLAIM.',RUNTIME='SOURCE→SIGNAL→CONTACT_FIELD→ROUTE_PRESSURE→STATE_CHANGE→DING→TRACE→RECOVERY→OUTPUT';
const enc=new TextEncoder(),now=()=>new Date().toISOString(),uid=(p='jmco')=>`${p}-${Date.now().toString(36)}-${crypto.getRandomValues(new Uint32Array(2)).join('-')}`;
const clone=v=>JSON.parse(JSON.stringify(v));
async function sha(s){const b=await crypto.subtle.digest('SHA-256',enc.encode(String(s)));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return'['+v.map(canonical).join(',')+']';return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}'}
function makeStore(key,persist){if(!persist){let v=null;return{load:()=>v?clone(v):null,save:x=>v=clone(x),clear:()=>v=null}}return{load(){try{return JSON.parse(localStorage.getItem(key)||'null')}catch{return null}},save:x=>localStorage.setItem(key,JSON.stringify(x)),clear:()=>localStorage.removeItem(key)}}
function create(c={}){const cfg=Object.freeze({recipientId:String(c.recipientId||'unknown'),bodyId:String(c.bodyId||'unknown'),bodyVersion:String(c.bodyVersion||'unknown'),consequence:String(c.consequence||'DECLARED_CONSEQUENCE'),inheritance:String(c.inheritance||'COMMON_CONTACT_ORGANS'),authorizationModel:String(c.authorizationModel||'NONE'),remoteAuthority:!!c.remoteAuthority,persistence:c.persistence!==false,cloudEvents:!!c.cloudEvents,claimBoundary:String(c.claimBoundary||'Only directly observed consequences earn a Ding; source patch/build/install/device/network results remain separately claim-gated.'),...c});
 const store=makeStore(`jm.estate.contact-organ/1.0/${cfg.bodyId}`,cfg.persistence),old=store.load(),boot=uid('boot');let s=old&&old.schema==='jm.contact.state/1.0'?old:{schema:'jm.contact.state/1.0',createdAt:now(),bootId:boot,bootAt:now(),priorBootId:null,priorBootAt:null,ready:false,active:false,revoked:false,blocked:false,consequenceEarned:false,seq:0,head:'0'.repeat(64),events:[]};if(old){s.priorBootId=s.bootId;s.priorBootAt=s.bootAt;s.bootId=boot;s.bootAt=now();s.active=false}const save=()=>store.save(s);
 async function trace(kind,detail={},earned=false){const e={schema:'jm.contact.event/1.0',id:uid('evt'),seq:++s.seq,at:now(),bootId:s.bootId,recipientId:cfg.recipientId,kind:String(kind),earned:!!earned,detail:clone(detail),previousHash:s.head};e.hash=await sha(`${e.previousHash}\n${canonical(e)}`);s.head=e.hash;s.events.unshift(e);s.events=s.events.slice(0,500);save();try{window.dispatchEvent(new CustomEvent('jm-contact-organ',{detail:clone(e)}))}catch{}return e}
 async function init(){save();await trace('TRACE.BOOT',{ownerLaw:OWNER,claimLaw:CLAIM,priorBootId:s.priorBootId,inheritance:cfg.inheritance});return api}
 async function ready(detail={}){if(s.revoked||s.blocked)throw Error('FAIL CLOSED: authority revoked/blocked');s.ready=true;save();return trace('TRACE.READY',{...detail,consequence:cfg.consequence})}
 async function begin(action=cfg.consequence,detail={}){if(!s.ready)throw Error('READINESS GATE');if(s.revoked||s.blocked)throw Error('FAIL CLOSED');s.active=true;save();return trace('TRACE.CONTACT_BEGIN',{action,detail})}
 async function ding(kind='DING.CONSEQUENCE',detail={}){if(!s.active)throw Error('NO DING: no active contact');if(detail.observed!==true)throw Error('NO DING: observed:true required');if(s.revoked||s.blocked)throw Error('NO DING: revoked/blocked');const e=await trace(String(kind).startsWith('DING.')?kind:`DING.${kind}`,{consequence:cfg.consequence,...detail},true);s.consequenceEarned=true;s.active=false;save();return e}
 async function fail(error,detail={}){s.active=false;save();return trace('TRACE.FAIL',{error:String(error),detail})}
 async function recover(detail={}){if(detail.observed!==true)throw Error('RECOVER requires observed:true');const e=await trace('DING.RECOVER',{...detail,priorBootId:s.priorBootId,priorBootAt:s.priorBootAt},true);s.ready=true;s.active=false;save();return e}
 const auth=()=>cfg.remoteAuthority||String(cfg.authorizationModel).toUpperCase()!=='NONE';
 async function revoke(detail={}){if(!auth())throw Error('REVOKE not semantically enabled');if(detail.observed!==true)throw Error('REVOKE requires observed:true');s.revoked=true;s.active=false;save();return trace('DING.REVOKE',detail,true)}
 async function block(detail={}){if(!auth())throw Error('BLOCK not semantically enabled');if(!s.revoked)throw Error('BLOCK requires revoked state');if(detail.observed!==true)throw Error('BLOCK requires observed:true');s.blocked=true;save();return trace('DING.BLOCK',detail,true)}
 async function verifyChain(){let prev='0'.repeat(64);for(const e of[...s.events].reverse()){if(e.previousHash!==prev)return{ok:false,id:e.id,reason:'previousHash'};const c={...e};delete c.hash;const h=await sha(`${c.previousHash}\n${canonical(c)}`);if(h!==e.hash)return{ok:false,id:e.id,reason:'hash'};prev=e.hash}return{ok:prev===s.head,head:prev,count:s.events.length}}
 function receipt(){return{schema:'jm.contact.receipt/1.0',exportedAt:now(),organVersion:VERSION,ownerLaw:OWNER,claimLaw:CLAIM,runtime:RUNTIME,config:{...cfg},state:clone(s),claim:{earned:!!s.consequenceEarned,declaredConsequence:cfg.consequence,boundary:cfg.claimBoundary}}}
 function exportReceipt(name){const text=JSON.stringify(receipt(),null,2),a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type:'application/json'}));a.href=u;a.download=name||`${cfg.recipientId}_CONTACT_RECEIPT.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
 async function reset({explicit=false}={}){if(!explicit)throw Error('Explicit reset required');store.clear();return true}
 const api=Object.freeze({version:VERSION,config:cfg,init,ready,begin,ding,fail,recover,revoke,block,verifyChain,receipt,exportReceipt,reset,state:()=>clone(s),laws:{OWNER,CLAIM,RUNTIME}});return api}
window.JMContactOrgan=Object.freeze({version:VERSION,create,laws:{OWNER,CLAIM,RUNTIME}});
})();
