using System;
using System.IO;
using System.Text;
using System.Collections.Generic;
using UnityEngine;
#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif
[Serializable] public class JMUnitySemanticPair { public string id; public string status; public JMUnitySemanticPair(string i,string s){id=i;status=s;} }
[Serializable] public class JMUnityReturnReceiptV04 { public string schema="JM.TargetBridge.HostReturnReceipt/0.4"; public string host="Unity"; public bool real_host=true; public string body_id="jm.spinbreak.v0.8/contact-slice-v0.1"; public string source_authority="JM"; public JMUnitySemanticPair[] semantic_results; public string[] unresolved_preserved=new[]{"spinbreak.full_contact_pressure_model", "spinbreak.full_three_body_ai", "spinbreak.full_visual_history_parity"}; public string status="OPEN"; }
public class JMTargetBridgeUnityContactHarness:MonoBehaviour{GameObject you,rival;Dictionary<string,string> sem=new();float spin=100f,stability=100f,integrity=100f;bool wakeUsed=false,wrote=false;JMUnityReturnReceiptV04 receipt=new();
[RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)] static void Boot(){if(FindFirstObjectByType<JMTargetBridgeUnityContactHarness>()==null)new GameObject("SPINBREAK JM TARGET BRIDGE").AddComponent<JMTargetBridgeUnityContactHarness>();}
void Start(){foreach(var id in new[]{"signal.route_right","move.you","signal.kic","kic.spin_cost","contact.you_rival_a","signal.wake","wake.stability","wake.spin","wake.integrity"})sem[id]="WAIT";you=GameObject.CreatePrimitive(PrimitiveType.Capsule);you.name="YOU";you.transform.position=new Vector3(-3f,0,0);rival=GameObject.CreatePrimitive(PrimitiveType.Sphere);rival.name="RIVAL_A";rival.transform.position=new Vector3(3f,0,0);if(Camera.main==null){var c=new GameObject("Main Camera");c.tag="MainCamera";var cam=c.AddComponent<Camera>();c.transform.position=new Vector3(0,6,-10);c.transform.LookAt(Vector3.zero);}if(FindFirstObjectByType<Light>()==null){var l=new GameObject("Directional Light");var li=l.AddComponent<Light>();li.type=LightType.Directional;l.transform.rotation=Quaternion.Euler(50,-30,0);}}
bool Down(KeyCode k){return Input.GetKey(k);}bool Press(KeyCode k){return Input.GetKeyDown(k);}
void Mark(string id){sem[id]="PASS";}void Update(){if(Down(KeyCode.RightArrow)){var b=you.transform.position;you.transform.position+=Vector3.right*3.5f*Time.deltaTime;if(you.transform.position.x>b.x){Mark("signal.route_right");Mark("move.you");}}if((Press(KeyCode.K)||Press(KeyCode.Space))&&sem["signal.kic"]!="PASS"){Mark("signal.kic");spin=Mathf.Clamp(spin-4.2f,0,100);Mark("kic.spin_cost");}if(you.GetComponent<Collider>().bounds.Intersects(rival.GetComponent<Collider>().bounds))Mark("contact.you_rival_a");if(Press(KeyCode.R)&&!wakeUsed){wakeUsed=true;Mark("signal.wake");stability=Mathf.Clamp(stability+16f,0,100);Mark("wake.stability");spin=Mathf.Clamp(spin+7f,0,100);Mark("wake.spin");integrity=Mathf.Clamp(integrity-3.5f,0,100);Mark("wake.integrity");}bool ok=true;foreach(var id in new[]{"signal.route_right","move.you","signal.kic","kic.spin_cost","contact.you_rival_a","signal.wake","wake.stability","wake.spin","wake.integrity"})ok&=sem[id]=="PASS";if(ok&&!wrote)WriteReceipt();}
void WriteReceipt(){wrote=true;var pairs=new List<JMUnitySemanticPair>();foreach(var kv in sem)pairs.Add(new JMUnitySemanticPair(kv.Key,kv.Value));receipt.semantic_results=pairs.ToArray();receipt.status="PASS";File.WriteAllText(Path.Combine(Application.persistentDataPath,"JM_TARGET_BRIDGE_UNITY_RETURN_RECEIPT.json"),JsonUtility.ToJson(receipt,true),Encoding.UTF8);Debug.Log("SPINBREAK TARGET BRIDGE UNITY CONTACT PASS");}
void OnGUI(){var st=new GUIStyle(GUI.skin.label){fontSize=19,wordWrap=true};st.normal.textColor=Color.black;string t="SPINBREAK v0.8 → UNITY\nspin: "+spin.ToString("F1")+" | stability: "+stability.ToString("F1")+" | integrity: "+integrity.ToString("F1")+"\nRIGHT + K/SPACE + CONTACT + R";foreach(var id in new[]{"signal.route_right","move.you","signal.kic","kic.spin_cost","contact.you_rival_a","signal.wake","wake.stability","wake.spin","wake.integrity"})t+=" | "+id+":"+sem[id];if(wrote)t+="\nBOUNDED SECOND-BUILD CONTACT: PASS";GUI.Label(new Rect(30,25,Screen.width-60,260),t,st);}}
