#!/usr/bin/env python3
import pathlib, sys

text = pathlib.Path(sys.argv[1]).read_text(errors='replace')
ordered = [
    'JM BOOT IMAGE LOADED',
    'ROUTEOS KERNEL ENTRY',
    'PRIVILEGED EXECUTION ACTIVE',
    'MEMORY INITIALISED: ALLOCATE/RELEASE PASS',
    'INTERRUPT ROUTE ACTIVE',
    'BODYREGISTRY: TWO USER BODIES REGISTERED',
    'ONEBODY GENERATED USER BODY 1 LOADED: SOURCE_SHA256',
    'PERMISSIONGATE: INT 0x80 CONTROLLED ENTRY ACTIVE',
    'DEVICE OUTPUT: JM-CONTROLLED SERIAL ACTIVE',
    'ROUTESCHEDULER: ENTERING USER BODY 1',
    'USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
    'GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN',
    'USER BODY 2 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
    'FAULTHOLD: USER BODY 2 INVALID OPCODE CAUGHT',
    'RECOVERYBODY: FAULTING BODY BLOCKED; SAFE BODY CONTINUES',
    'USER BODY 1 -> SYSTEM CALL TRACE_READ -> PERMISSIONGATE PASS',
    'GENERATED USER BODY 1 -> SYSTEM CALL ROUTE_STATE -> PERMISSIONGATE PASS -> ROUTEOS STATE 1 -> KERNEL RETURN',
]
pos = -1
for item in ordered:
    new = text.find(item, pos + 1)
    if new < 0:
        raise SystemExit(f'HOLD: missing or out-of-order trace: {item}')
    pos = new

if 'TIMER TICK ' not in text or '-> ROUTESCHEDULER' not in text:
    raise SystemExit('HOLD: no dynamic PIT timer -> RouteScheduler receipt')

print('ONEBODY_TO_ROUTEOS_KERNEL_TRACE PASS')
print('GENERATED_CPL3_BODY PASS')
print('ROUTEOS_STATE_CHANGE PASS')
print('POST_FAULT_GENERATED_BODY_CONTINUATION PASS')
print('TIMER_DRIVEN_SCHEDULER_TRACE PASS')
